# Analysis of APT data (statistical distributions)

**System**
* Alloy composition: $Al_{0.1}FeNiCrCo$
* Lattice: FCC
* Lattice constant: 3.57A

**APT measurement**
* Detector efficiency: 33%
* position uncertainty (standard deviation): 5A (in x-, y-directions) and 3A in z-direction

## Setup

In [1]:
# Notebook settings

# code development settings (automatically reload modified modules)
%load_ext autoreload
%autoreload 2

# plotting backend
%matplotlib inline

In [2]:
# basic libraries

import os, sys
import re
import copy
import glob
from itertools import product
import pickle
from collections import Counter
import numpy as np
#import scipy.io
from scipy.stats import multinomial, chi2
from scipy.optimize import fmin
from sklearn.neighbors import NearestNeighbors

# plotting
import matplotlib.pyplot as plt

# data handling
# import pyUSID as usid
# import h5py
# import pandas as pd
# import xarray as xr

# parallelization
# from subprocess import Popen, PIPE
import multiprocessing as mp

In [3]:
# local library
sys.path.append('../../../force_fields/statmechlib')
from statmechlib.read_write import read_lattice_mc, read_modeldef, write_modeldef
from statmechlib.preprocessing import get_stats_latt, cfg_replicate, latt_to_real_coords, add_experimental_noise
from statmechlib.preprocessing import real_coords, select_core, get_knn_stats
from statmechlib.forcefields import sd2, get_chi2_two, get_s2_two, data_lists, loss_sd2_hist
from statmechlib.forcefields import make_reference_matrices, make_target_matrices

In [5]:
# project directories
data_raw = '../data/interim'
src_dir = '../src/utils'
sim_dir = '../sim/enth_model'
sim_dir_m1 = '../sim/m1'
sim_dir_m2 = '../sim/m2'
sim_dir_m3 = '../sim/m3'

In [6]:
sys.path.append(src_dir)
from utils import *

## Read target data

In [7]:
# compositions, concentrations, atom types
element = ['Al','Fe','Ni','Cr','Co']
ntype = len(element)

# numbers of KNNs of a particular atom i of type ti
knn = list(range(1,13))
#knn += [20, 40, 100, 200, 500, 1000]

In [8]:
targets = {}
for k in knn:
    targets[k] = read_pairwise(os.path.join(data_raw, f'RamaTest_Clean_PatternK{k}_PairWise'), k, ntype)

In [9]:
# count statistics and concentrations
counts = np.sum(targets[knn[5]], axis=2)[:,0]
assert np.array_equal(counts, np.sum(targets[knn[0]], axis=2)[:,0])

conc = counts/np.sum(counts)
tot_counts = np.sum(counts)

In [14]:
# kksum = 0
# for kk in targets[1][:]:
#     ks = sum([i*p for i, p in enumerate(kk[-1])])
#     print(ks)
#     kksum += ks
# print(kksum)

## Generate random distributions (null hypothesis)

* Assume that there are no interactioins between particles and for each KNN generate multinomial distributions with parameters (probabilities) set to mole fractions.

In [15]:
null_reference = {}
null_counts = {}
for k in knn:
    null_reference[k] = get_binomials(k, conc)
    null_counts[k] = null_reference[k]*tot_counts

## Read reference data from MC simulations

In [16]:
# read in a set of trajectories
#trj_dirs = ['txinf', 'tx500', 'tx700', 'tx1000']
#trj_dirs = ['1x700']
trj_dirs = ['3x700']

In [18]:
trjs = {}
for key in trj_dirs:
    # read trajectory info
    trjs[key] = read_lattice_mc(os.path.join(sim_dir_m3, key), verbose=1)

Reading ../sim/m3/3x700/lg.hst
Reading ../sim/m3/3x700/lg.run
Reading ../sim/m3/3x700/lg.xyz
Reading ../sim/m3/3x700/lg.mld


In [19]:
trjs['3x700']['ref_params']

array([ 0.  , -2.97, -7.  , -1.05, -4.  ,  0.  , -0.78, -0.06, -0.48,
        0.  , -0.24, -0.17,  0.  ,  0.04,  0.  ])

## Add experimental noise

In [20]:
unknown_frac = counts[-1]/np.sum(counts)

# analyze configurations
for key, trj in trjs.items():
    if key not in ['3x700']:
        continue
    print('trj:', key)

    # convert from lattice to real coordinates
    trj = latt_to_real_coords(trj, 3.57/2.0)

    # model of experimental noise
    xyzs, typs = add_experimental_noise(trj, loss_rate=0.67, disp=np.array([5.0, 5.0, 3.0]), unknown_frac=0.0)
    trjs[key]['xyz_noise'] = xyzs
    trjs[key]['atom_type_noise'] = typs

trj: 3x700


In [21]:
# 1. replicate configurations to avoid dealing with periodic boundary conditions
# 2. convert to real coordinates
# 3. select core
for key, trj in trjs.items():
    if key not in ['3x700']:
        continue

    print('trj:', key)
    xyzs = []
    boxs = []
    tis = []
    for xyz, box, ti in zip(trj['xyz_noise'], trj['box'], trj['atom_type_noise']):
        xyz_big, box_big = cfg_replicate(xyz, box, vec_a=2, vec_b=2, vec_c=2)
        xyzs.append(xyz_big)
        boxs.append(box_big)
        tis.append(np.tile(ti, 2*2*2))                                          

    trj['xyz_noise'] = xyzs
    trj['box_noise'] = boxs
    trj['atom_type_noise'] = tis
    
    trj['xyz_noise'] = real_coords(trj['xyz_noise'], trj['box_noise'])
    
    trj['xyz_core'], trj['atom_type_core'] = select_core(trj['xyz_noise'], trj['box_noise'], trj['atom_type_noise'])

trj: 3x700


In [22]:
# with open('../data/working/trjs.pickle', 'wb') as fo:
#     pickle.dump(trjs, fo)

### Neighbor statistics

In [23]:
knns = list(range(1,13))
#knns += [20, 40, 100, 200]

# create nighbor model with the maximum of nearest neighbors (1000). KDTree should make this Nlog(N)
neigh = NearestNeighbors(n_neighbors=knns[-1], algorithm='kd_tree', n_jobs=4)

In [24]:
for key, trj in trjs.items():
    if key not in ['3x700']:
        continue

    print('trj:', key)

    knn_stats = []
    for it, (cor, xyz, ti_core, ti) in enumerate(zip(trj['xyz_core'], trj['xyz_noise'], trj['atom_type_core'], trj['atom_type_noise'])):
        print(it, len(ti_core), len(ti))
        if it < 2000:
            continue
        neigh.fit(xyz)
        dist, ind = neigh.kneighbors(cor, n_neighbors=knns[-1]+1)
        assert np.array_equal(dist[:,0], np.zeros(dist.shape[0])), "First neighbor is not center"
        knn_stats.append(get_knn_stats(ind, ti_core, ti, knns=knns))

    trj['knn'] = knn_stats

trj: 3x700
0 470 3760
1 487 3896
2 445 3560
3 435 3480
4 451 3608
5 457 3656
6 447 3576
7 447 3576
8 459 3672
9 469 3752
10 467 3736
11 442 3536
12 438 3504
13 442 3536
14 432 3456
15 429 3432
16 448 3584
17 432 3456
18 430 3440
19 474 3792
20 438 3504
21 426 3408
22 415 3320
23 433 3464
24 472 3776
25 442 3536
26 462 3696
27 428 3424
28 462 3696
29 448 3584
30 431 3448
31 485 3880
32 461 3688
33 461 3688
34 465 3720
35 424 3392
36 452 3616
37 444 3552
38 434 3472
39 431 3448
40 456 3648
41 438 3504
42 476 3808
43 443 3544
44 476 3808
45 460 3680
46 502 4016
47 449 3592
48 448 3584
49 465 3720
50 435 3480
51 482 3856
52 446 3568
53 476 3808
54 445 3560
55 453 3624
56 442 3536
57 446 3568
58 483 3864
59 432 3456
60 479 3832
61 477 3816
62 465 3720
63 446 3568
64 480 3840
65 482 3856
66 453 3624
67 442 3536
68 448 3584
69 436 3488
70 430 3440
71 437 3496
72 454 3632
73 456 3648
74 452 3616
75 453 3624
76 455 3640
77 442 3536
78 439 3512
79 452 3616
80 463 3704
81 474 3792
82 442 3536
83 

700 478 3824
701 466 3728
702 442 3536
703 430 3440
704 474 3792
705 439 3512
706 458 3664
707 445 3560
708 471 3768
709 457 3656
710 436 3488
711 459 3672
712 451 3608
713 451 3608
714 433 3464
715 437 3496
716 476 3808
717 436 3488
718 446 3568
719 447 3576
720 450 3600
721 477 3816
722 432 3456
723 460 3680
724 417 3336
725 436 3488
726 468 3744
727 462 3696
728 436 3488
729 429 3432
730 461 3688
731 444 3552
732 451 3608
733 444 3552
734 455 3640
735 437 3496
736 455 3640
737 467 3736
738 477 3816
739 440 3520
740 459 3672
741 474 3792
742 404 3232
743 448 3584
744 407 3256
745 433 3464
746 466 3728
747 448 3584
748 450 3600
749 434 3472
750 437 3496
751 461 3688
752 449 3592
753 444 3552
754 454 3632
755 437 3496
756 467 3736
757 470 3760
758 447 3576
759 465 3720
760 453 3624
761 405 3240
762 451 3608
763 440 3520
764 441 3528
765 482 3856
766 467 3736
767 482 3856
768 450 3600
769 440 3520
770 426 3408
771 447 3576
772 460 3680
773 435 3480
774 472 3776
775 451 3608
776 436 3488

1940 463 3704
1941 434 3472
1942 490 3920
1943 461 3688
1944 464 3712
1945 448 3584
1946 417 3336
1947 418 3344
1948 429 3432
1949 410 3280
1950 449 3592
1951 429 3432
1952 451 3608
1953 482 3856
1954 442 3536
1955 436 3488
1956 448 3584
1957 439 3512
1958 462 3696
1959 439 3512
1960 462 3696
1961 447 3576
1962 464 3712
1963 437 3496
1964 440 3520
1965 464 3712
1966 439 3512
1967 494 3952
1968 437 3496
1969 455 3640
1970 444 3552
1971 458 3664
1972 453 3624
1973 450 3600
1974 434 3472
1975 452 3616
1976 452 3616
1977 434 3472
1978 442 3536
1979 451 3608
1980 457 3656
1981 439 3512
1982 466 3728
1983 431 3448
1984 444 3552
1985 446 3568
1986 452 3616
1987 474 3792
1988 462 3696
1989 470 3760
1990 409 3272
1991 452 3616
1992 466 3728
1993 473 3784
1994 453 3624
1995 446 3568
1996 449 3592
1997 447 3576
1998 459 3672
1999 430 3440
2000 449 3592
2001 459 3672
2002 470 3760
2003 433 3464
2004 436 3488
2005 466 3728
2006 476 3808
2007 437 3496
2008 472 3776
2009 447 3576
2010 462 3696
2011 4

2527 433 3464
2528 447 3576
2529 443 3544
2530 448 3584
2531 465 3720
2532 477 3816
2533 449 3592
2534 439 3512
2535 471 3768
2536 455 3640
2537 478 3824
2538 438 3504
2539 475 3800
2540 437 3496
2541 462 3696
2542 428 3424
2543 439 3512
2544 459 3672
2545 449 3592
2546 452 3616
2547 428 3424
2548 441 3528
2549 472 3776
2550 484 3872
2551 431 3448
2552 466 3728
2553 450 3600
2554 472 3776
2555 409 3272
2556 466 3728
2557 462 3696
2558 447 3576
2559 433 3464
2560 432 3456
2561 471 3768
2562 436 3488
2563 467 3736
2564 456 3648
2565 447 3576
2566 423 3384
2567 437 3496
2568 456 3648
2569 439 3512
2570 462 3696
2571 474 3792
2572 491 3928
2573 438 3504
2574 421 3368
2575 432 3456
2576 438 3504
2577 447 3576
2578 436 3488
2579 490 3920
2580 453 3624
2581 459 3672
2582 446 3568
2583 428 3424
2584 431 3448
2585 457 3656
2586 451 3608
2587 464 3712
2588 469 3752
2589 465 3720
2590 429 3432
2591 451 3608
2592 430 3440
2593 449 3592
2594 461 3688
2595 466 3728
2596 448 3584
2597 439 3512
2598 4

3113 475 3800
3114 453 3624
3115 467 3736
3116 435 3480
3117 440 3520
3118 428 3424
3119 479 3832
3120 455 3640
3121 474 3792
3122 461 3688
3123 457 3656
3124 458 3664
3125 459 3672
3126 440 3520
3127 455 3640
3128 438 3504
3129 472 3776
3130 457 3656
3131 462 3696
3132 455 3640
3133 438 3504
3134 443 3544
3135 447 3576
3136 421 3368
3137 476 3808
3138 452 3616
3139 428 3424
3140 457 3656
3141 443 3544
3142 462 3696
3143 447 3576
3144 479 3832
3145 459 3672
3146 472 3776
3147 443 3544
3148 438 3504
3149 439 3512
3150 459 3672
3151 443 3544
3152 457 3656
3153 456 3648
3154 447 3576
3155 490 3920
3156 451 3608
3157 459 3672
3158 464 3712
3159 451 3608
3160 461 3688
3161 459 3672
3162 435 3480
3163 457 3656
3164 440 3520
3165 423 3384
3166 431 3448
3167 467 3736
3168 463 3704
3169 415 3320
3170 436 3488
3171 429 3432
3172 432 3456
3173 472 3776
3174 460 3680
3175 456 3648
3176 451 3608
3177 469 3752
3178 457 3656
3179 455 3640
3180 438 3504
3181 459 3672
3182 440 3520
3183 458 3664
3184 4

3699 431 3448
3700 459 3672
3701 494 3952
3702 456 3648
3703 447 3576
3704 463 3704
3705 469 3752
3706 445 3560
3707 452 3616
3708 467 3736
3709 474 3792
3710 459 3672
3711 447 3576
3712 461 3688
3713 480 3840
3714 426 3408
3715 438 3504
3716 435 3480
3717 426 3408
3718 464 3712
3719 446 3568
3720 441 3528
3721 445 3560
3722 412 3296
3723 479 3832
3724 435 3480
3725 438 3504
3726 442 3536
3727 452 3616
3728 433 3464
3729 452 3616
3730 479 3832
3731 461 3688
3732 455 3640
3733 427 3416
3734 460 3680
3735 470 3760
3736 495 3960
3737 444 3552
3738 422 3376
3739 471 3768
3740 412 3296
3741 461 3688
3742 463 3704
3743 455 3640
3744 439 3512
3745 462 3696
3746 447 3576
3747 422 3376
3748 441 3528
3749 438 3504
3750 467 3736
3751 459 3672
3752 444 3552
3753 437 3496
3754 457 3656
3755 466 3728
3756 439 3512
3757 464 3712
3758 443 3544
3759 447 3576
3760 435 3480
3761 450 3600
3762 447 3576
3763 445 3560
3764 445 3560
3765 450 3600
3766 429 3432
3767 450 3600
3768 452 3616
3769 449 3592
3770 4

4286 475 3800
4287 431 3448
4288 462 3696
4289 459 3672
4290 447 3576
4291 438 3504
4292 441 3528
4293 456 3648
4294 471 3768
4295 427 3416
4296 458 3664
4297 452 3616
4298 430 3440
4299 438 3504
4300 446 3568
4301 436 3488
4302 455 3640
4303 476 3808
4304 453 3624
4305 455 3640
4306 455 3640
4307 455 3640
4308 456 3648
4309 465 3720
4310 444 3552
4311 454 3632
4312 479 3832
4313 478 3824
4314 433 3464
4315 464 3712
4316 458 3664
4317 420 3360
4318 452 3616
4319 454 3632
4320 451 3608
4321 442 3536
4322 464 3712
4323 469 3752
4324 482 3856
4325 457 3656
4326 455 3640
4327 463 3704
4328 453 3624
4329 464 3712
4330 474 3792
4331 493 3944
4332 433 3464
4333 440 3520
4334 442 3536
4335 457 3656
4336 445 3560
4337 451 3608
4338 440 3520
4339 450 3600
4340 434 3472
4341 429 3432
4342 445 3560
4343 471 3768
4344 488 3904
4345 436 3488
4346 460 3680
4347 416 3328
4348 424 3392
4349 453 3624
4350 463 3704
4351 423 3384
4352 468 3744
4353 443 3544
4354 464 3712
4355 458 3664
4356 432 3456
4357 4

4872 440 3520
4873 441 3528
4874 456 3648
4875 419 3352
4876 468 3744
4877 469 3752
4878 451 3608
4879 427 3416
4880 426 3408
4881 460 3680
4882 471 3768
4883 434 3472
4884 469 3752
4885 419 3352
4886 463 3704
4887 406 3248
4888 442 3536
4889 438 3504
4890 435 3480
4891 461 3688
4892 429 3432
4893 462 3696
4894 432 3456
4895 465 3720
4896 452 3616
4897 450 3600
4898 447 3576
4899 451 3608
4900 438 3504
4901 444 3552
4902 454 3632
4903 424 3392
4904 449 3592
4905 441 3528
4906 460 3680
4907 451 3608
4908 456 3648
4909 451 3608
4910 418 3344
4911 467 3736
4912 453 3624
4913 458 3664
4914 476 3808
4915 471 3768
4916 459 3672
4917 466 3728
4918 435 3480
4919 460 3680
4920 460 3680
4921 469 3752
4922 436 3488
4923 487 3896
4924 469 3752
4925 468 3744
4926 455 3640
4927 450 3600
4928 441 3528
4929 433 3464
4930 411 3288
4931 445 3560
4932 449 3592
4933 492 3936
4934 430 3440
4935 444 3552
4936 445 3560
4937 441 3528
4938 447 3576
4939 465 3720
4940 454 3632
4941 461 3688
4942 444 3552
4943 4

5458 449 3592
5459 457 3656
5460 464 3712
5461 448 3584
5462 468 3744
5463 455 3640
5464 468 3744
5465 485 3880
5466 442 3536
5467 450 3600
5468 439 3512
5469 449 3592
5470 462 3696
5471 443 3544
5472 451 3608
5473 473 3784
5474 440 3520
5475 447 3576
5476 456 3648
5477 453 3624
5478 444 3552
5479 479 3832
5480 458 3664
5481 455 3640
5482 438 3504
5483 445 3560
5484 437 3496
5485 433 3464
5486 442 3536
5487 451 3608
5488 453 3624
5489 431 3448
5490 444 3552
5491 439 3512
5492 473 3784
5493 463 3704
5494 433 3464
5495 462 3696
5496 439 3512
5497 418 3344
5498 487 3896
5499 444 3552
5500 454 3632
5501 455 3640
5502 478 3824
5503 493 3944
5504 483 3864
5505 437 3496
5506 471 3768
5507 425 3400
5508 433 3464
5509 457 3656
5510 470 3760
5511 443 3544
5512 463 3704
5513 460 3680
5514 452 3616
5515 472 3776
5516 435 3480
5517 467 3736
5518 435 3480
5519 460 3680
5520 454 3632
5521 443 3544
5522 465 3720
5523 436 3488
5524 452 3616
5525 445 3560
5526 421 3368
5527 433 3464
5528 421 3368
5529 4

6044 430 3440
6045 465 3720
6046 438 3504
6047 451 3608
6048 441 3528
6049 450 3600
6050 457 3656
6051 414 3312
6052 435 3480
6053 440 3520
6054 484 3872
6055 460 3680
6056 441 3528
6057 429 3432
6058 479 3832
6059 460 3680
6060 461 3688
6061 461 3688
6062 412 3296
6063 420 3360
6064 469 3752
6065 450 3600
6066 405 3240
6067 473 3784
6068 445 3560
6069 434 3472
6070 446 3568
6071 485 3880
6072 438 3504
6073 451 3608
6074 477 3816
6075 472 3776
6076 465 3720
6077 458 3664
6078 442 3536
6079 444 3552
6080 474 3792
6081 466 3728
6082 458 3664
6083 459 3672
6084 474 3792
6085 475 3800
6086 449 3592
6087 449 3592
6088 448 3584
6089 477 3816
6090 457 3656
6091 449 3592
6092 437 3496
6093 457 3656
6094 425 3400
6095 452 3616
6096 464 3712
6097 464 3712
6098 442 3536
6099 441 3528
6100 465 3720
6101 457 3656
6102 447 3576
6103 450 3600
6104 456 3648
6105 444 3552
6106 451 3608
6107 453 3624
6108 431 3448
6109 463 3704
6110 453 3624
6111 414 3312
6112 455 3640
6113 432 3456
6114 422 3376
6115 4

6631 439 3512
6632 444 3552
6633 460 3680
6634 451 3608
6635 443 3544
6636 454 3632
6637 442 3536
6638 430 3440
6639 464 3712
6640 480 3840
6641 461 3688
6642 451 3608
6643 443 3544
6644 472 3776
6645 461 3688
6646 453 3624
6647 451 3608
6648 437 3496
6649 446 3568
6650 468 3744
6651 457 3656
6652 463 3704
6653 470 3760
6654 466 3728
6655 447 3576
6656 463 3704
6657 449 3592
6658 499 3992
6659 467 3736
6660 448 3584
6661 451 3608
6662 436 3488
6663 449 3592
6664 461 3688
6665 453 3624
6666 442 3536
6667 424 3392
6668 455 3640
6669 457 3656
6670 454 3632
6671 458 3664
6672 450 3600
6673 448 3584
6674 437 3496
6675 450 3600
6676 467 3736
6677 456 3648
6678 447 3576
6679 456 3648
6680 428 3424
6681 450 3600
6682 433 3464
6683 467 3736
6684 464 3712
6685 446 3568
6686 470 3760
6687 484 3872
6688 444 3552
6689 469 3752
6690 446 3568
6691 437 3496
6692 480 3840
6693 420 3360
6694 452 3616
6695 469 3752
6696 446 3568
6697 426 3408
6698 455 3640
6699 457 3656
6700 464 3712
6701 438 3504
6702 4

7217 455 3640
7218 439 3512
7219 429 3432
7220 480 3840
7221 451 3608
7222 452 3616
7223 487 3896
7224 448 3584
7225 444 3552
7226 467 3736
7227 446 3568
7228 451 3608
7229 446 3568
7230 443 3544
7231 436 3488
7232 464 3712
7233 455 3640
7234 441 3528
7235 437 3496
7236 431 3448
7237 461 3688
7238 437 3496
7239 433 3464
7240 453 3624
7241 473 3784
7242 449 3592
7243 473 3784
7244 463 3704
7245 440 3520
7246 446 3568
7247 454 3632
7248 443 3544
7249 456 3648
7250 453 3624
7251 460 3680
7252 426 3408
7253 445 3560
7254 447 3576
7255 457 3656
7256 433 3464
7257 447 3576
7258 457 3656
7259 467 3736
7260 423 3384
7261 432 3456
7262 457 3656
7263 427 3416
7264 468 3744
7265 455 3640
7266 460 3680
7267 463 3704
7268 437 3496
7269 461 3688
7270 458 3664
7271 485 3880
7272 446 3568
7273 466 3728
7274 445 3560
7275 481 3848
7276 483 3864
7277 426 3408
7278 438 3504
7279 426 3408
7280 490 3920
7281 449 3592
7282 479 3832
7283 490 3920
7284 446 3568
7285 454 3632
7286 459 3672
7287 438 3504
7288 4

7804 466 3728
7805 450 3600
7806 458 3664
7807 435 3480
7808 480 3840
7809 451 3608
7810 459 3672
7811 460 3680
7812 431 3448
7813 428 3424
7814 445 3560
7815 468 3744
7816 476 3808
7817 455 3640
7818 471 3768
7819 463 3704
7820 471 3768
7821 431 3448
7822 452 3616
7823 425 3400
7824 444 3552
7825 449 3592
7826 434 3472
7827 412 3296
7828 437 3496
7829 470 3760
7830 447 3576
7831 471 3768
7832 438 3504
7833 469 3752
7834 470 3760
7835 433 3464
7836 458 3664
7837 463 3704
7838 475 3800
7839 466 3728
7840 432 3456
7841 460 3680
7842 444 3552
7843 443 3544
7844 470 3760
7845 441 3528
7846 434 3472
7847 452 3616
7848 438 3504
7849 448 3584
7850 465 3720
7851 471 3768
7852 467 3736
7853 431 3448
7854 457 3656
7855 473 3784
7856 453 3624
7857 442 3536
7858 440 3520
7859 466 3728
7860 444 3552
7861 465 3720
7862 438 3504
7863 434 3472
7864 416 3328
7865 440 3520
7866 454 3632
7867 454 3632
7868 454 3632
7869 425 3400
7870 464 3712
7871 468 3744
7872 475 3800
7873 452 3616
7874 423 3384
7875 4

8390 458 3664
8391 449 3592
8392 427 3416
8393 456 3648
8394 443 3544
8395 476 3808
8396 447 3576
8397 461 3688
8398 435 3480
8399 467 3736
8400 437 3496
8401 452 3616
8402 454 3632
8403 449 3592
8404 426 3408
8405 454 3632
8406 453 3624
8407 418 3344
8408 464 3712
8409 470 3760
8410 472 3776
8411 471 3768
8412 477 3816
8413 452 3616
8414 455 3640
8415 449 3592
8416 448 3584
8417 424 3392
8418 459 3672
8419 441 3528
8420 436 3488
8421 461 3688
8422 459 3672
8423 453 3624
8424 458 3664
8425 452 3616
8426 467 3736
8427 464 3712
8428 472 3776
8429 478 3824
8430 427 3416
8431 469 3752
8432 474 3792
8433 460 3680
8434 442 3536
8435 460 3680
8436 436 3488
8437 458 3664
8438 467 3736
8439 442 3536
8440 468 3744
8441 446 3568
8442 439 3512
8443 432 3456
8444 467 3736
8445 437 3496
8446 454 3632
8447 443 3544
8448 440 3520
8449 454 3632
8450 463 3704
8451 452 3616
8452 435 3480
8453 473 3784
8454 435 3480
8455 449 3592
8456 475 3800
8457 434 3472
8458 469 3752
8459 456 3648
8460 458 3664
8461 4

8976 457 3656
8977 459 3672
8978 470 3760
8979 466 3728
8980 447 3576
8981 455 3640
8982 435 3480
8983 458 3664
8984 459 3672
8985 469 3752
8986 450 3600
8987 427 3416
8988 420 3360
8989 417 3336
8990 478 3824
8991 491 3928
8992 451 3608
8993 445 3560
8994 416 3328
8995 472 3776
8996 451 3608
8997 492 3936
8998 470 3760
8999 453 3624
9000 460 3680
9001 491 3928
9002 489 3912
9003 462 3696
9004 444 3552
9005 444 3552
9006 478 3824
9007 463 3704
9008 419 3352
9009 443 3544
9010 425 3400
9011 424 3392
9012 451 3608
9013 458 3664
9014 440 3520
9015 424 3392
9016 451 3608
9017 445 3560
9018 449 3592
9019 496 3968
9020 435 3480
9021 468 3744
9022 473 3784
9023 472 3776
9024 477 3816
9025 466 3728
9026 446 3568
9027 438 3504
9028 433 3464
9029 456 3648
9030 422 3376
9031 430 3440
9032 499 3992
9033 449 3592
9034 442 3536
9035 484 3872
9036 456 3648
9037 451 3608
9038 444 3552
9039 460 3680
9040 449 3592
9041 432 3456
9042 493 3944
9043 443 3544
9044 474 3792
9045 438 3504
9046 454 3632
9047 4

9563 429 3432
9564 428 3424
9565 443 3544
9566 481 3848
9567 455 3640
9568 428 3424
9569 488 3904
9570 439 3512
9571 462 3696
9572 452 3616
9573 467 3736
9574 430 3440
9575 457 3656
9576 429 3432
9577 440 3520
9578 452 3616
9579 462 3696
9580 433 3464
9581 442 3536
9582 458 3664
9583 455 3640
9584 434 3472
9585 447 3576
9586 458 3664
9587 434 3472
9588 482 3856
9589 457 3656
9590 434 3472
9591 466 3728
9592 473 3784
9593 426 3408
9594 451 3608
9595 439 3512
9596 462 3696
9597 443 3544
9598 473 3784
9599 446 3568
9600 460 3680
9601 441 3528
9602 469 3752
9603 435 3480
9604 472 3776
9605 425 3400
9606 504 4032
9607 453 3624
9608 422 3376
9609 429 3432
9610 462 3696
9611 467 3736
9612 461 3688
9613 475 3800
9614 463 3704
9615 439 3512
9616 450 3600
9617 444 3552
9618 477 3816
9619 441 3528
9620 433 3464
9621 466 3728
9622 440 3520
9623 476 3808
9624 461 3688
9625 455 3640
9626 455 3640
9627 480 3840
9628 451 3608
9629 471 3768
9630 505 4040
9631 460 3680
9632 457 3656
9633 447 3576
9634 4

10139 450 3600
10140 444 3552
10141 455 3640
10142 438 3504
10143 465 3720
10144 462 3696
10145 460 3680
10146 460 3680
10147 462 3696
10148 450 3600
10149 490 3920
10150 434 3472
10151 440 3520
10152 493 3944
10153 459 3672
10154 456 3648
10155 420 3360
10156 454 3632
10157 423 3384
10158 434 3472
10159 427 3416
10160 460 3680
10161 465 3720
10162 467 3736
10163 444 3552
10164 457 3656
10165 468 3744
10166 439 3512
10167 443 3544
10168 455 3640
10169 449 3592
10170 457 3656
10171 458 3664
10172 480 3840
10173 422 3376
10174 452 3616
10175 429 3432
10176 440 3520
10177 486 3888
10178 441 3528
10179 476 3808
10180 459 3672
10181 476 3808
10182 464 3712
10183 470 3760
10184 445 3560
10185 447 3576
10186 445 3560
10187 444 3552
10188 459 3672
10189 482 3856
10190 445 3560
10191 469 3752
10192 442 3536
10193 438 3504
10194 414 3312
10195 445 3560
10196 468 3744
10197 454 3632
10198 438 3504
10199 453 3624
10200 432 3456
10201 467 3736
10202 473 3784
10203 453 3624
10204 453 3624
10205 477 

10686 454 3632
10687 493 3944
10688 457 3656
10689 470 3760
10690 459 3672
10691 486 3888
10692 457 3656
10693 471 3768
10694 423 3384
10695 473 3784
10696 442 3536
10697 477 3816
10698 443 3544
10699 469 3752
10700 454 3632
10701 463 3704
10702 467 3736
10703 448 3584
10704 463 3704
10705 468 3744
10706 471 3768
10707 447 3576
10708 451 3608
10709 452 3616
10710 437 3496
10711 477 3816
10712 448 3584
10713 468 3744
10714 442 3536
10715 460 3680
10716 464 3712
10717 433 3464
10718 441 3528
10719 442 3536
10720 481 3848
10721 447 3576
10722 419 3352
10723 478 3824
10724 434 3472
10725 457 3656
10726 449 3592
10727 448 3584
10728 466 3728
10729 427 3416
10730 483 3864
10731 449 3592
10732 464 3712
10733 442 3536
10734 435 3480
10735 413 3304
10736 473 3784
10737 430 3440
10738 438 3504
10739 482 3856
10740 452 3616
10741 470 3760
10742 456 3648
10743 457 3656
10744 448 3584
10745 443 3544
10746 447 3576
10747 473 3784
10748 474 3792
10749 439 3512
10750 445 3560
10751 441 3528
10752 462 

11234 457 3656
11235 447 3576
11236 455 3640
11237 451 3608
11238 447 3576
11239 437 3496
11240 458 3664
11241 478 3824
11242 440 3520
11243 435 3480
11244 448 3584
11245 457 3656
11246 452 3616
11247 457 3656
11248 444 3552
11249 445 3560
11250 454 3632
11251 464 3712
11252 462 3696
11253 455 3640
11254 466 3728
11255 458 3664
11256 447 3576
11257 451 3608
11258 480 3840
11259 464 3712
11260 451 3608
11261 467 3736
11262 436 3488
11263 451 3608
11264 452 3616
11265 459 3672
11266 463 3704
11267 427 3416
11268 445 3560
11269 432 3456
11270 454 3632
11271 438 3504
11272 462 3696
11273 452 3616
11274 464 3712
11275 464 3712
11276 476 3808
11277 479 3832
11278 481 3848
11279 454 3632
11280 452 3616
11281 428 3424
11282 484 3872
11283 445 3560
11284 468 3744
11285 437 3496
11286 438 3504
11287 460 3680
11288 471 3768
11289 443 3544
11290 436 3488
11291 442 3536
11292 443 3544
11293 449 3592
11294 474 3792
11295 475 3800
11296 433 3464
11297 460 3680
11298 450 3600
11299 439 3512
11300 405 

11781 436 3488
11782 419 3352
11783 461 3688
11784 455 3640
11785 460 3680
11786 476 3808
11787 467 3736
11788 454 3632
11789 450 3600
11790 456 3648
11791 446 3568
11792 460 3680
11793 438 3504
11794 453 3624
11795 461 3688
11796 473 3784
11797 430 3440
11798 461 3688
11799 463 3704
11800 415 3320
11801 473 3784
11802 443 3544
11803 437 3496
11804 431 3448
11805 415 3320
11806 446 3568
11807 441 3528
11808 463 3704
11809 434 3472
11810 446 3568
11811 464 3712
11812 442 3536
11813 454 3632
11814 426 3408
11815 413 3304
11816 460 3680
11817 476 3808
11818 457 3656
11819 486 3888
11820 486 3888
11821 452 3616
11822 464 3712
11823 464 3712
11824 473 3784
11825 458 3664
11826 430 3440
11827 502 4016
11828 439 3512
11829 454 3632
11830 453 3624
11831 421 3368
11832 428 3424
11833 509 4072
11834 427 3416
11835 432 3456
11836 422 3376
11837 454 3632
11838 448 3584
11839 453 3624
11840 464 3712
11841 469 3752
11842 458 3664
11843 481 3848
11844 477 3816
11845 443 3544
11846 411 3288
11847 480 

In [25]:
ti[ind[2]], ti_core[2], np.array_equal(dist[:,0], np.zeros(dist.shape[0]))

(array([4, 2, 2, 2, 3, 4, 3, 5, 4, 5, 2, 2, 5]), 4, True)

In [26]:
knn_stats[-1][0]

array([[[ 13,   0],
        [ 11,   2],
        [  7,   6],
        [ 12,   1],
        [  9,   4]],

       [[106,   1],
        [ 92,  15],
        [ 71,  36],
        [ 83,  24],
        [ 76,  31]],

       [[132,   5],
        [103,  34],
        [ 92,  45],
        [113,  24],
        [108,  29]],

       [[ 93,   2],
        [ 70,  25],
        [ 71,  24],
        [ 66,  29],
        [ 80,  15]],

       [[101,   4],
        [ 81,  24],
        [ 70,  35],
        [ 91,  14],
        [ 77,  28]]])

In [28]:
trjs['3x700']['atom_type_core'][1]

array([5, 3, 5, 2, 4, 5, 2, 2, 4, 3, 2, 5, 4, 5, 3, 3, 2, 4, 3, 2, 5, 3,
       4, 5, 3, 1, 4, 5, 5, 5, 2, 4, 2, 3, 5, 3, 2, 3, 1, 4, 2, 5, 5, 5,
       3, 3, 4, 1, 4, 4, 4, 3, 2, 2, 4, 4, 3, 4, 5, 2, 2, 3, 5, 2, 4, 4,
       5, 2, 4, 4, 2, 4, 4, 5, 4, 2, 3, 4, 3, 3, 3, 5, 3, 4, 3, 2, 3, 5,
       4, 5, 5, 4, 1, 4, 5, 5, 2, 4, 3, 2, 2, 5, 4, 2, 4, 4, 5, 2, 2, 2,
       5, 5, 2, 2, 5, 4, 1, 5, 2, 3, 5, 3, 5, 5, 4, 4, 1, 4, 3, 3, 3, 3,
       3, 2, 3, 4, 5, 5, 4, 5, 4, 3, 2, 5, 4, 5, 4, 2, 2, 2, 2, 5, 2, 2,
       4, 4, 3, 4, 3, 2, 5, 3, 5, 4, 4, 3, 4, 4, 4, 5, 1, 2, 3, 4, 2, 4,
       4, 3, 5, 4, 4, 3, 2, 3, 4, 3, 4, 3, 4, 3, 3, 4, 3, 4, 3, 5, 2, 5,
       3, 4, 2, 5, 4, 4, 5, 3, 4, 5, 4, 3, 3, 4, 5, 3, 4, 4, 5, 5, 3, 2,
       3, 4, 3, 3, 5, 4, 3, 1, 3, 3, 3, 2, 3, 4, 5, 2, 2, 5, 5, 3, 3, 2,
       4, 3, 4, 3, 5, 3, 5, 4, 3, 2, 3, 2, 2, 4, 3, 3, 4, 4, 2, 4, 5, 4,
       3, 4, 2, 3, 5, 3, 2, 5, 2, 1, 5, 5, 5, 2, 4, 4, 3, 5, 3, 2, 5, 2,
       5, 5, 5, 5, 5, 4, 2, 4, 3, 4, 4, 5, 4, 5, 5,

In [29]:
# with open('../data/working/trjs_knn.pickle', 'wb') as fo:
#     pickle.dump(trjs, fo)

In [30]:
trjs['3x700'].keys()

dict_keys(['energy', 'interaction_stats', 'temp', 'box_latt', 'xyz_latt', 'atom_type', 'ref_params', 'box', 'xyz', 'xyz_noise', 'atom_type_noise', 'box_noise', 'xyz_core', 'atom_type_core', 'knn'])

In [32]:
knn_all = {}
ppp_all = {}
conc_all = []

for key in ['3x700']:
    hists = trjs[key]['knn']
    print(len(hists), len(hists[0]), hists[0][0].shape)
    
    # sum histograms
    print(key)
    knn_trj = []
    ppp_trj = []
    for i, k in enumerate(knns):
        hhh = np.zeros((ntype, ntype, k+1), dtype=float)
        for hst in hists:
            hhh += hst[i]
        knn_trj.append(hhh)
        hsum = np.sum(hhh, axis=2)
        #print(i, hsum[:,0])
        if i == 0:
            counts_all = hsum[:,1]
            conc_all = counts_all/np.sum(counts_all)
        ppp = hhh/hsum[:,:,None]
        ppp_trj.append(ppp)
    
    knn_all[key] = knn_trj
    ppp_all[key] = ppp_trj
    # get probability distributions
tot_counts_all = np.sum(counts_all)
print(conc_all, counts_all/10001, tot_counts_all)
print(conc, counts, tot_counts)

10001 12 (5, 5, 2)
3x700
[0.02546358 0.25093573 0.25065104 0.23394963 0.23900003] [ 11.52814719 113.60633937 113.47745225 105.91620838 108.20267973] 4527761.0
[0.02557753 0.25074298 0.25070882 0.23409538 0.23887529] [ 30699 300950 300909 280969 286706] 1200233


In [33]:
trjs['3x700']['knn'][0][0].shape

(5, 5, 2)

In [41]:
#  optimize only unlike parameters

select = []
for i in range(1, ntype+1):
    for j in range(i, ntype+1):
        if i == 1 and (j == 2 or j == 3 or j == 5):
            select.append(True)
        else:
            select.append(False)
#         #print(i,j)
#         if i == j:
#             select.append(False)
#         else:
#             select.append(True)

#         hist_ave = average_histogram(pars_in, params_list, X_list[key], df_est[key][0], hist_list[key])
#         cb1 = np.sqrt(hist_ave).dot(np.sqrt(hist_targ[key]))
#         s2 = np.arccos(cb1)**2

In [42]:
sum(select)

3

In [43]:
X_list, beta_ref, pars_list, ene_ref, hist_list = data_lists(trjs, minval=-10000)

In [44]:
len(trjs['3x700']['temp']), len(beta_ref[0]), len(hist_list[0])

(12001, 10000, 10000)

In [47]:
pars_list, knns

([array([ 0.  , -2.97, -7.  , -1.05, -4.  ,  0.  , -0.78, -0.06, -0.48,
          0.  , -0.24, -0.17,  0.  ,  0.04,  0.  ])],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [48]:
X_ref, pars_ref, hist_ref = make_reference_matrices(hist_list, X_list, pars_list, select, knn_max=12)

In [49]:
targets[1].shape

(5, 5, 2)

In [53]:
hist_targ = make_target_matrices(targets)[:12,:,:]

In [54]:
X_ref[0].shape, pars_ref[0].shape, beta_ref[0].shape, hist_ref[0].shape, hist_targ.shape

((10000, 3), (3,), (10000,), (10000, 12, 5, 5), (12, 5, 5))

In [56]:
pars_in = pars_ref[0]

In [57]:
pars_in

array([-2.97, -7.  , -4.  ])

In [58]:
output = fmin(loss_sd2_hist, pars_in, args=(X_ref[0], pars_ref[0], beta_ref[0], hist_ref[0], hist_targ))

0
[0.02537256 0.25019517 0.25549522 0.23141514 0.2375219 ]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999823079846188
1
[0.02555675 0.24963558 0.25134852 0.23357041 0.23988874]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.999995772830877
2
[0.02593644 0.25129409 0.25008151 0.23402369 0.23866426]
[0.02657282 0.25029826 0.24985295 0.23417711 0.23909886]
0.9999974400310616
3
[0.02505561 0.25135956 0.25071377 0.23386558 0.23900548]
[0.02528393 0.25189968 0.24920543 0.23405073 0.23956024]
0.9999982793740678
4
[0.02524047 0.2517005  0.25054065 0.23439325 0.23812512]
[0.02555231 0.25130622 0.251512   0.23550955 0.23611993]
0.9999961917289245
0
[0.0252598  0.24980483 0.25357385 0.23301556 0.23834597]
[0.02482166 0.24798853 0.2603505  0.23067527 0.23616404]
0.9999695833187903
1
[0.02558404 0.24967915 0.25108885 0.23419758 0.23945038]
[0.0251487  0.24989035 0.25074431 0.23483635 0.2393803 ]
0.9999987645552888
2
[0.02578619 0.25102003 0.25013263 0.23442553 0.2386356

0
[0.02531032 0.2508127  0.25423644 0.23155264 0.2380879 ]
[0.02495195 0.24948152 0.25761425 0.23158735 0.23636492]
0.9999913379865336
1
[0.0254456  0.24992834 0.25101847 0.23419581 0.23941178]
[0.02516642 0.24964944 0.25077311 0.23493493 0.2394761 ]
0.999999252807755
2
[0.02582706 0.25126434 0.24998775 0.23407162 0.23884923]
[0.02608042 0.25082999 0.24989172 0.23408406 0.23911382]
0.9999995555826298
3
[0.02519918 0.25113856 0.25066902 0.2339939  0.23899933]
[0.02522402 0.2510971  0.24997182 0.23437698 0.23933008]
0.9999996178465463
4
[0.02536644 0.25136372 0.25057764 0.23407137 0.23862083]
[0.02522212 0.25124925 0.2508028  0.23519564 0.2375302 ]
0.9999985673699541
0
[0.02517801 0.25088021 0.25389698 0.23183679 0.23820801]
[0.02511948 0.24896111 0.25746302 0.23173859 0.23671781]
0.9999907496191058
1
[0.02544753 0.24994567 0.25113932 0.23409306 0.23937441]
[0.02515748 0.24979612 0.25082857 0.23482021 0.23939762]
0.999999242903542
2
[0.02578405 0.2512796  0.25005615 0.23400787 0.23887233

[0.02536745 0.25149892 0.25099405 0.23515989 0.23697969]
0.9999977481297684
0
[0.02528066 0.25091659 0.253837   0.2318925  0.23807325]
[0.02478257 0.24909606 0.25764357 0.23218997 0.23628783]
0.9999882937523694
1
[0.02545834 0.24983024 0.25105583 0.23429484 0.23936075]
[0.02516099 0.24979764 0.2506948  0.23482173 0.23952484]
0.9999993358504322
2
[0.02579939 0.25123537 0.2500291  0.23409336 0.23884278]
[0.02617137 0.25100944 0.24955784 0.23418376 0.23907759]
0.9999991646442862
3
[0.02523916 0.2511655  0.25062752 0.23406722 0.2389006 ]
[0.02513516 0.25117148 0.24985176 0.23452979 0.23931181]
0.9999994431392912
4
[0.02540416 0.25126713 0.25054445 0.23403858 0.23874567]
[0.02522026 0.25119949 0.25092604 0.2354377  0.23721652]
0.9999974875227706
0
[0.02531204 0.25080323 0.2542517  0.23154776 0.23808526]
[0.02495195 0.24948152 0.25761425 0.23158735 0.23636492]
0.9999913994082417
1
[0.02544564 0.2499263  0.25101863 0.23419594 0.23941349]
[0.02516642 0.24964944 0.25077311 0.23493493 0.2394761 

0
[0.02538442 0.25014955 0.25553638 0.23139672 0.23753293]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.999982549071456
1
[0.02555792 0.24963373 0.25134102 0.23356797 0.23989936]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.9999957436903567
2
[0.02594084 0.25127685 0.25008077 0.23401962 0.23868192]
[0.02657282 0.25029826 0.24985295 0.23417711 0.23909886]
0.9999974910776033
3
[0.0250509  0.25134645 0.25071729 0.23386061 0.23902474]
[0.02528393 0.25189968 0.24920543 0.23405073 0.23956024]
0.999998266115325
4
[0.02523804 0.25169457 0.25054559 0.23440488 0.23811691]
[0.02555231 0.25130622 0.251512   0.23550955 0.23611993]
0.9999962223408287
0
[0.02526192 0.24979444 0.25360635 0.23299692 0.23834037]
[0.02482166 0.24798853 0.2603505  0.23067527 0.23616404]
0.9999698676952994
1
[0.02558373 0.24966852 0.25108651 0.23420118 0.23946006]
[0.0251487  0.24989035 0.25074431 0.23483635 0.2393803 ]
0.999998766044723
2
[0.0257881  0.25101384 0.25013862 0.23442003 0.2386394 ]

0
[0.02538375 0.25014126 0.25554238 0.23140107 0.23753154]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999825901770778
1
[0.025557   0.24963136 0.25133728 0.23356879 0.23990556]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.9999957327392157
2
[0.02594111 0.25127298 0.25007738 0.23401945 0.23868908]
[0.02657282 0.25029826 0.24985295 0.23417711 0.23909886]
0.9999975002920845
3
[0.02504972 0.25134189 0.25072133 0.23385999 0.23902708]
[0.02528393 0.25189968 0.24920543 0.23405073 0.23956024]
0.9999982559036954
4
[0.02523662 0.25169656 0.25054672 0.23440562 0.23811448]
[0.02555231 0.25130622 0.251512   0.23550955 0.23611993]
0.9999962241898492
0
[0.02525983 0.24979593 0.2536098  0.23300015 0.23833429]
[0.02482166 0.24798853 0.2603505  0.23067527 0.23616404]
0.9999699027316984
1
[0.0255833  0.24966324 0.25108502 0.2342036  0.23946484]
[0.0251487  0.24989035 0.25074431 0.23483635 0.2393803 ]
0.9999987684135233
2
[0.02578794 0.25101102 0.25013992 0.23441999 0.238641

0
[0.02512924 0.250764   0.25397892 0.23174943 0.23837841]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999851395935972
1
[0.02545336 0.24987095 0.25107892 0.23430883 0.23928793]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991102175227
2
[0.02579448 0.25102501 0.25009904 0.23419627 0.23888521]
[0.02624714 0.2512105  0.2495281  0.23411729 0.23889698]
0.9999988320365836
3
[0.02524481 0.25104345 0.25064802 0.23416726 0.23889647]
[0.02516381 0.25103481 0.2498345  0.23447605 0.23949083]
0.9999994013558312
4
[0.02545244 0.2512839  0.25055562 0.23407323 0.23863481]
[0.02536745 0.25149892 0.25099405 0.23515989 0.23697969]
0.999997776601795
0
[0.02528284 0.2508829  0.2538808  0.23189742 0.23805604]
[0.02478257 0.24909606 0.25764357 0.23218997 0.23628783]
0.999988540003121
1
[0.02545796 0.24982216 0.25105443 0.23429914 0.23936631]
[0.02516099 0.24979764 0.2506948  0.23482173 0.23952484]
0.9999993410369721
2
[0.02580254 0.25122664 0.25003686 0.23409174 0.23884222

0
[0.02528324 0.25086726 0.25390013 0.23190202 0.23804735]
[0.02478257 0.24909606 0.25764357 0.23218997 0.23628783]
0.9999886545058732
1
[0.02545768 0.24981821 0.2510536  0.23430165 0.23936886]
[0.02516099 0.24979764 0.2506948  0.23482173 0.23952484]
0.9999993440405681
2
[0.0258038  0.25122276 0.25004009 0.23409151 0.23884183]
[0.02617137 0.25100944 0.24955784 0.23418376 0.23907759]
0.9999991775053204
3
[0.02523374 0.25116105 0.25062119 0.23406916 0.23891487]
[0.02513516 0.25117148 0.24985176 0.23452979 0.23931181]
0.9999994604175306
4
[0.0253988  0.25126451 0.2505431  0.23405394 0.23873965]
[0.02522026 0.25119949 0.25092604 0.2354377  0.23721652]
0.9999975292086689
0
[0.02531231 0.25076918 0.25430319 0.23154163 0.23807369]
[0.02495195 0.24948152 0.25761425 0.23158735 0.23636492]
0.9999916317442102
1
[0.02544483 0.2499175  0.25101399 0.23420221 0.23942147]
[0.02516642 0.24964944 0.25077311 0.23493493 0.2394761 ]
0.9999992646008975
2
[0.02583092 0.25124682 0.24999565 0.2340694  0.238857

0
[0.02519705 0.25071987 0.25349746 0.23231898 0.23826664]
[0.0243439  0.24910692 0.25798886 0.23187509 0.23668523]
0.9999837429223479
1
[0.02549089 0.24968374 0.2509993  0.23434942 0.23947666]
[0.02515257 0.2494822  0.25089107 0.23476768 0.23970649]
0.9999992880119508
2
[0.02580315 0.25094943 0.25003135 0.23433969 0.23887638]
[0.02646758 0.25116896 0.24956493 0.23395999 0.23883854]
0.9999976778941806
3
[0.0251538  0.25122908 0.25061824 0.2341935  0.23880538]
[0.02517953 0.25107515 0.24990183 0.23470442 0.23913907]
0.9999995311429258
4
[0.0254584  0.25123893 0.25064802 0.23423673 0.23841792]
[0.0253442  0.25180498 0.25096091 0.23509914 0.23679077]
0.9999979387340301
0
[0.02512678 0.25074451 0.25400641 0.23174254 0.23837976]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999852952438516
1
[0.02545327 0.24986143 0.2510742  0.23431213 0.23929897]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991201255558
2
[0.02579559 0.25101919 0.2501006  0.23419571 0.238888

0
[0.02528148 0.25085322 0.25391486 0.23191026 0.23804017]
[0.02478257 0.24909606 0.25764357 0.23218997 0.23628783]
0.9999887577418455
1
[0.02545716 0.24981556 0.25105093 0.23430517 0.23937118]
[0.02516099 0.24979764 0.2506948  0.23482173 0.23952484]
0.999999348880413
2
[0.0258045  0.25121978 0.25004233 0.23409169 0.2388417 ]
[0.02617137 0.25100944 0.24955784 0.23418376 0.23907759]
0.9999991794963727
3
[0.02523188 0.25116221 0.25061715 0.23407033 0.23891844]
[0.02513516 0.25117148 0.24985176 0.23452979 0.23931181]
0.9999994673775159
4
[0.02539659 0.25126366 0.25054158 0.23405846 0.23873971]
[0.02522026 0.25119949 0.25092604 0.2354377  0.23721652]
0.9999975391011797
0
[0.02530965 0.25076121 0.25431442 0.23154284 0.23807188]
[0.02495195 0.24948152 0.25761425 0.23158735 0.23636492]
0.9999916911006185
1
[0.02544433 0.24991583 0.25101075 0.23420573 0.23942335]
[0.02516642 0.24964944 0.25077311 0.23493493 0.2394761 ]
0.9999992700297843
2
[0.02583103 0.25124352 0.24999549 0.23406913 0.2388608

0
[0.02531248 0.25076371 0.25431141 0.23154104 0.23807136]
[0.02495195 0.24948152 0.25761425 0.23158735 0.23636492]
0.9999916689455705
1
[0.02544472 0.24991587 0.25101354 0.23420315 0.23942272]
[0.02516642 0.24964944 0.25077311 0.23493493 0.2394761 ]
0.9999992662379298
2
[0.02583134 0.25124468 0.24999642 0.23406932 0.23885824]
[0.02608042 0.25082999 0.24989172 0.23408406 0.23911382]
0.9999995758083802
3
[0.02519328 0.25112722 0.25065814 0.233997   0.23902436]
[0.02522402 0.2510971  0.24997182 0.23437698 0.23933008]
0.9999996337258542
4
[0.02536029 0.25136095 0.25057031 0.23409832 0.23861013]
[0.02522212 0.25124925 0.2508028  0.23519564 0.2375302 ]
0.999998618703681
0
[0.02517713 0.25085121 0.25396161 0.231822   0.23818805]
[0.02511948 0.24896111 0.25746302 0.23173859 0.23671781]
0.9999910618226562
1
[0.0254467  0.2499362  0.2511322  0.23409427 0.23939063]
[0.02515748 0.24979612 0.25082857 0.23482021 0.23939762]
0.999999250011205
2
[0.02578715 0.25126183 0.2500633  0.23400561 0.23888211

[0.02573048 0.24933711 0.25615167 0.23160038 0.23718036]
0.9999916866046897
1
[0.02549132 0.24988487 0.25111981 0.23412676 0.23937724]
[0.02523575 0.24965576 0.25073833 0.23487689 0.23949327]
0.9999992723750784
2
[0.02576665 0.25128938 0.25011478 0.23394463 0.23888456]
[0.02606203 0.25066748 0.25031754 0.23388732 0.23906563]
0.9999993470652178
3
[0.02521804 0.25114428 0.2506023  0.23396037 0.23907501]
[0.02511701 0.2509526  0.2499443  0.23451306 0.23947304]
0.999999468982373
4
[0.02545326 0.25140577 0.25058639 0.23419739 0.23835719]
[0.02529909 0.2509651  0.25049389 0.23505821 0.23818371]
0.9999993714453087
0
[0.02482375 0.25094141 0.25379618 0.23187568 0.23856298]
[0.02575151 0.2491849  0.25593668 0.23184942 0.23727749]
0.9999910869657604
1
[0.02549505 0.24986548 0.25109176 0.23413957 0.23940815]
[0.02526243 0.2497594  0.25070821 0.23478862 0.23948134]
0.999999427164324
2
[0.02578191 0.25138662 0.25003766 0.23390887 0.23888494]
[0.02601391 0.25059585 0.25032485 0.23403209 0.2390333 ]


0
[0.02487515 0.25073622 0.2538395  0.23196321 0.23858592]
[0.02573048 0.24933711 0.25615167 0.23160038 0.23718036]
0.9999916771684612
1
[0.02549131 0.24988497 0.25111925 0.23412738 0.23937709]
[0.02523575 0.24965576 0.25073833 0.23487689 0.23949327]
0.9999992730650301
2
[0.02576637 0.25128964 0.2501143  0.23394487 0.23888482]
[0.02606203 0.25066748 0.25031754 0.23388732 0.23906563]
0.9999993460370957
3
[0.0252179  0.25114485 0.25060156 0.23396056 0.23907513]
[0.02511701 0.2509526  0.2499443  0.23451306 0.23947304]
0.9999994696711557
4
[0.0254531  0.25140583 0.25058614 0.23419756 0.23835736]
[0.02529909 0.2509651  0.25049389 0.23505821 0.23818371]
0.999999371802898
0
[0.02482329 0.2509429  0.25379453 0.23187656 0.23856272]
[0.02575151 0.2491849  0.25593668 0.23184942 0.23727749]
0.9999910769828506
1
[0.02549503 0.24986562 0.25109125 0.23414015 0.23940794]
[0.02526243 0.2497594  0.25070821 0.23478862 0.23948134]
0.9999994277728714
2
[0.02578165 0.25138678 0.25003732 0.23390906 0.2388851

0
[0.02479829 0.25091264 0.25381951 0.23180525 0.23866432]
[0.02588304 0.24950596 0.25548878 0.23188052 0.23724171]
0.9999907725177513
1
[0.02548798 0.24987775 0.25109216 0.23414402 0.2393981 ]
[0.02529988 0.24980423 0.25061167 0.23475688 0.23952733]
0.9999994991295105
2
[0.02577116 0.2514001  0.25006064 0.23392893 0.23883916]
[0.02600731 0.25067712 0.25020798 0.23407326 0.23903434]
0.9999994285667726
3
[0.02524139 0.2510661  0.25062131 0.23393619 0.23913501]
[0.02517211 0.25093071 0.24998339 0.23437817 0.23953562]
0.9999995757482505
4
[0.02544992 0.25148266 0.25059418 0.23418503 0.2382882 ]
[0.02529885 0.25107543 0.25037088 0.2350131  0.23824173]
0.9999994137034368
0.2831036177563377 [-3.16621193 -8.          1.        ]
0
[0.0253944  0.25006277 0.25560031 0.23139419 0.23754833]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999829489298713
1
[0.02555469 0.24961959 0.2513133  0.23357452 0.23993789]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.999995673685835

0
[0.02479957 0.25090816 0.25382275 0.23180394 0.23866559]
[0.02588304 0.24950596 0.25548878 0.23188052 0.23724171]
0.9999907959298973
1
[0.02548813 0.24987732 0.25109365 0.2341425  0.23939839]
[0.02529988 0.24980423 0.25061167 0.23475688 0.23952733]
0.9999994972100379
2
[0.02577188 0.25139983 0.25006106 0.23392862 0.23883861]
[0.02600731 0.25067712 0.25020798 0.23407326 0.23903434]
0.9999994303025281
3
[0.02524183 0.25106511 0.25062275 0.23393544 0.23913487]
[0.02517211 0.25093071 0.24998339 0.23437817 0.23953562]
0.9999995742403024
4
[0.02545048 0.25148259 0.25059494 0.23418436 0.23828763]
[0.02529885 0.25107543 0.25037088 0.2350131  0.23824173]
0.9999994121752243
0.2830270094436347 [-2.51988272 -8.          1.        ]
0
[0.02540124 0.25005752 0.25560675 0.23137496 0.23755952]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999829754504601
1
[0.02555705 0.24962245 0.25131562 0.23357368 0.2399312 ]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.999995683844272

0
[0.02532139 0.25075244 0.25432997 0.23153338 0.23806282]
[0.02495195 0.24948152 0.25761425 0.23158735 0.23636492]
0.999991725820149
1
[0.02544553 0.24991043 0.25102057 0.23419848 0.23942498]
[0.02516642 0.24964944 0.25077311 0.23493493 0.2394761 ]
0.9999992602026668
2
[0.02583364 0.25124104 0.25000183 0.23406964 0.23885386]
[0.02608042 0.25082999 0.24989172 0.23408406 0.23911382]
0.9999995810571509
3
[0.02519469 0.25111554 0.25066487 0.23399587 0.23902903]
[0.02522402 0.2510971  0.24997182 0.23437698 0.23933008]
0.9999996308222225
4
[0.02536101 0.25136203 0.25057207 0.23410111 0.23860378]
[0.02522212 0.25124925 0.2508028  0.23519564 0.2375302 ]
0.9999986284409853
0
[0.025182   0.25084089 0.25398086 0.23181334 0.23818291]
[0.02511948 0.24896111 0.25746302 0.23173859 0.23671781]
0.9999911529385084
1
[0.02544785 0.24993071 0.25113726 0.23409094 0.23939325]
[0.02515748 0.24979612 0.25082857 0.23482021 0.23939762]
0.9999992433738489
2
[0.02578894 0.25125888 0.25006938 0.23400469 0.2388781

0
[0.02529859 0.25084903 0.25394197 0.23187482 0.23803559]
[0.02478257 0.24909606 0.25764357 0.23218997 0.23628783]
0.9999887747292432
1
[0.02545953 0.2498069  0.25106797 0.23429473 0.23937087]
[0.02516099 0.24979764 0.2506948  0.23482173 0.23952484]
0.9999993300145664
2
[0.02580875 0.25121454 0.25004835 0.23408874 0.23883961]
[0.02617137 0.25100944 0.24955784 0.23418376 0.23907759]
0.9999991917966581
3
[0.02523414 0.25114261 0.25063297 0.23406467 0.2389256 ]
[0.02513516 0.25117148 0.24985176 0.23452979 0.23931181]
0.99999945271914
4
[0.0254008  0.25126523 0.25054669 0.23406226 0.23872502]
[0.02522026 0.25119949 0.25092604 0.2354377  0.23721652]
0.9999975624631354
0
[0.02532832 0.25074649 0.25433951 0.2315273  0.23805839]
[0.02495195 0.24948152 0.25761425 0.23158735 0.23636492]
0.9999917459702968
1
[0.02544621 0.24990704 0.25102656 0.23419411 0.23942608]
[0.02516642 0.24964944 0.25077311 0.23493493 0.2394761 ]
0.9999992543199515
2
[0.02583519 0.25123954 0.25000559 0.23406989 0.23884979

0
[0.02515984 0.25072534 0.25405858 0.23170682 0.23834943]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999855068671577
1
[0.02545475 0.24985272 0.2510919  0.23430979 0.23929085]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991078965915
2
[0.02579915 0.25101411 0.25010846 0.234193   0.23888529]
[0.02624714 0.2512105  0.2495281  0.23411729 0.23889698]
0.9999988450952495
3
[0.02524115 0.25102411 0.25065854 0.23415974 0.23891646]
[0.02516381 0.25103481 0.2498345  0.23447605 0.23949083]
0.9999994053199063
4
[0.02545519 0.25127824 0.25055537 0.2340911  0.2386201 ]
[0.02536745 0.25149892 0.25099405 0.23515989 0.23697969]
0.9999978189018411
0
[0.0252999  0.25084858 0.2539441  0.23187201 0.23803542]
[0.02478257 0.24909606 0.25764357 0.23218997 0.23628783]
0.9999887758906358
1
[0.0254597  0.24980619 0.25106928 0.23429393 0.2393709 ]
[0.02516099 0.24979764 0.2506948  0.23482173 0.23952484]
0.9999993285931696
2
[0.02580908 0.25121412 0.25004878 0.23408853 0.238839

0
[0.02515984 0.25072534 0.25405858 0.23170682 0.23834943]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999855068671577
1
[0.02545475 0.24985272 0.2510919  0.23430979 0.23929085]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991078965915
2
[0.02579915 0.25101411 0.25010846 0.234193   0.23888529]
[0.02624714 0.2512105  0.2495281  0.23411729 0.23889698]
0.9999988450952495
3
[0.02524115 0.25102411 0.25065854 0.23415974 0.23891646]
[0.02516381 0.25103481 0.2498345  0.23447605 0.23949083]
0.9999994053199063
4
[0.02545519 0.25127824 0.25055537 0.2340911  0.2386201 ]
[0.02536745 0.25149892 0.25099405 0.23515989 0.23697969]
0.9999978189018411
0
[0.0252999  0.25084858 0.2539441  0.23187201 0.23803542]
[0.02478257 0.24909606 0.25764357 0.23218997 0.23628783]
0.9999887758906358
1
[0.0254597  0.24980619 0.25106928 0.23429393 0.2393709 ]
[0.02516099 0.24979764 0.2506948  0.23482173 0.23952484]
0.9999993285931696
2
[0.02580908 0.25121412 0.25004878 0.23408853 0.238839

0
[0.02494262 0.25103077 0.25390515 0.231831   0.23829045]
[0.02554915 0.24932046 0.25621175 0.2319149  0.23700374]
0.9999932348217908
1
[0.02545964 0.24987208 0.25111866 0.23412318 0.23942644]
[0.02523712 0.2498525  0.25058869 0.23492496 0.23939673]
0.9999992725775417
2
[0.02577631 0.25125413 0.25020125 0.23388525 0.23888307]
[0.02609981 0.25081374 0.2501561  0.23383777 0.23909259]
0.9999993739001554
3
[0.02521929 0.2511586  0.2506485  0.23393884 0.23903476]
[0.02510795 0.25083827 0.25000267 0.23458025 0.23947086]
0.999999360145845
4
[0.025428   0.25142149 0.25063088 0.23415124 0.23836839]
[0.02531242 0.25098107 0.25054237 0.23501737 0.23814678]
0.9999994082420891
0
[0.02488513 0.25070614 0.25387201 0.23194697 0.23858974]
[0.02573048 0.24933711 0.25615167 0.23160038 0.23718036]
0.9999918771743626
1
[0.02549145 0.2498827  0.2511313  0.23411399 0.23938056]
[0.02523575 0.24965576 0.25073833 0.23487689 0.23949327]
0.9999992581999828
2
[0.02577246 0.25128403 0.25012481 0.23393966 0.2388790

0
[0.02523643 0.25070678 0.25352256 0.23227417 0.23826006]
[0.0243439  0.24910692 0.25798886 0.23187509 0.23668523]
0.9999835617284856
1
[0.02549355 0.24968675 0.25101614 0.23434104 0.23946251]
[0.02515257 0.2494822  0.25089107 0.23476768 0.23970649]
0.9999992692608727
2
[0.02580938 0.2509456  0.25002806 0.23434099 0.23887597]
[0.02646758 0.25116896 0.24956493 0.23395999 0.23883854]
0.9999977177317976
3
[0.02515159 0.25120535 0.25063675 0.23418115 0.23882516]
[0.02517953 0.25107515 0.24990183 0.23470442 0.23913907]
0.9999995203832991
4
[0.02546381 0.25123361 0.25064953 0.23425145 0.2384016 ]
[0.0253442  0.25180498 0.25096091 0.23509914 0.23679077]
0.9999979711642383
0
[0.02515984 0.25072534 0.25405858 0.23170682 0.23834943]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999855068671577
1
[0.02545475 0.24985272 0.2510919  0.23430979 0.23929085]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991078965915
2
[0.02579915 0.25101411 0.25010846 0.234193   0.238885

[0.02517211 0.25093071 0.24998339 0.23437817 0.23953562]
0.9999995656943967
4
[0.02545356 0.25148219 0.25059888 0.23418058 0.23828479]
[0.02529885 0.25107543 0.25037088 0.2350131  0.23824173]
0.9999994035809664
0.28273233698425115 [ 1. -8.  1.]
0
[0.02542515 0.25004003 0.25562861 0.23130681 0.2375994 ]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999830565325551
1
[0.02556556 0.24963149 0.25132429 0.23357115 0.23990751]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.9999957184752554
2
[0.02594877 0.25123391 0.25008896 0.23404788 0.23868048]
[0.02657282 0.25029826 0.24985295 0.23417711 0.23909886]
0.999997581506055
3
[0.02503966 0.25132976 0.25072027 0.23383587 0.23907445]
[0.02528393 0.25189968 0.24920543 0.23405073 0.23956024]
0.9999982467326796
4
[0.02523164 0.25165521 0.25055237 0.23445183 0.23810895]
[0.02555231 0.25130622 0.251512   0.23550955 0.23611993]
0.9999962939415873
0
[0.02530264 0.24972768 0.2536879  0.23293411 0.23834767]
[0.02482166 0.24798853

0
[0.02480634 0.25088331 0.25384081 0.2317961  0.23867344]
[0.02588304 0.24950596 0.25548878 0.23188052 0.23724171]
0.9999909203273015
1
[0.02548895 0.24987489 0.25110165 0.23413434 0.23940017]
[0.02529988 0.24980423 0.25061167 0.23475688 0.23952733]
0.9999994868443624
2
[0.02577583 0.25139825 0.25006342 0.23392694 0.23883556]
[0.02600731 0.25067712 0.25020798 0.23407326 0.23903434]
0.9999994398109864
3
[0.02524417 0.25105977 0.25063087 0.23393105 0.23913415]
[0.02517211 0.25093071 0.24998339 0.23437817 0.23953562]
0.9999995656943967
4
[0.02545356 0.25148219 0.25059888 0.23418058 0.23828479]
[0.02529885 0.25107543 0.25037088 0.2350131  0.23824173]
0.9999994035809664
0.28273233698425115 [ 1. -8.  1.]
0
[0.02542515 0.25004003 0.25562861 0.23130681 0.2375994 ]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999830565325551
1
[0.02556556 0.24963149 0.25132429 0.23357115 0.23990751]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.9999957184752554
2
[0.02594877 0.25123

0
[0.02515984 0.25072534 0.25405858 0.23170682 0.23834943]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999855068671577
1
[0.02545475 0.24985272 0.2510919  0.23430979 0.23929085]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991078965915
2
[0.02579915 0.25101411 0.25010846 0.234193   0.23888529]
[0.02624714 0.2512105  0.2495281  0.23411729 0.23889698]
0.9999988450952495
3
[0.02524115 0.25102411 0.25065854 0.23415974 0.23891646]
[0.02516381 0.25103481 0.2498345  0.23447605 0.23949083]
0.9999994053199063
4
[0.02545519 0.25127824 0.25055537 0.2340911  0.2386201 ]
[0.02536745 0.25149892 0.25099405 0.23515989 0.23697969]
0.9999978189018411
0
[0.0252999  0.25084858 0.2539441  0.23187201 0.23803542]
[0.02478257 0.24909606 0.25764357 0.23218997 0.23628783]
0.9999887758906358
1
[0.0254597  0.24980619 0.25106928 0.23429393 0.2393709 ]
[0.02516099 0.24979764 0.2506948  0.23482173 0.23952484]
0.9999993285931696
2
[0.02580908 0.25121412 0.25004878 0.23408853 0.238839

0
[0.02507067 0.25103963 0.25386794 0.23173209 0.23828967]
[0.02538763 0.24876217 0.25686912 0.2318398  0.23714127]
0.9999917991663752
1
[0.02544898 0.24987064 0.25110245 0.23413546 0.23944247]
[0.02522637 0.24975619 0.25063923 0.23489907 0.23947915]
0.9999993305406453
2
[0.02577276 0.25122872 0.25013972 0.23396582 0.23889297]
[0.02605148 0.2507386  0.25028995 0.2338103  0.23910966]
0.9999994568566866
3
[0.02522884 0.25112963 0.25070577 0.23396013 0.23897563]
[0.0250993  0.25104816 0.24992081 0.23456102 0.23937071]
0.9999993313989548
4
[0.02540915 0.25145472 0.25066476 0.23411058 0.23836079]
[0.02530249 0.25110174 0.25067665 0.23503737 0.23788175]
0.9999993036778413
0
[0.02494262 0.25103077 0.25390515 0.231831   0.23829045]
[0.02554915 0.24932046 0.25621175 0.2319149  0.23700374]
0.9999932348217908
1
[0.02545964 0.24987208 0.25111866 0.23412318 0.23942644]
[0.02523712 0.2498525  0.25058869 0.23492496 0.23939673]
0.9999992725775417
2
[0.02577631 0.25125413 0.25020125 0.23388525 0.238883

0
[0.02494262 0.25103077 0.25390515 0.231831   0.23829045]
[0.02554915 0.24932046 0.25621175 0.2319149  0.23700374]
0.9999932348217908
1
[0.02545964 0.24987208 0.25111866 0.23412318 0.23942644]
[0.02523712 0.2498525  0.25058869 0.23492496 0.23939673]
0.9999992725775417
2
[0.02577631 0.25125413 0.25020125 0.23388525 0.23888307]
[0.02609981 0.25081374 0.2501561  0.23383777 0.23909259]
0.9999993739001554
3
[0.02521929 0.2511586  0.2506485  0.23393884 0.23903476]
[0.02510795 0.25083827 0.25000267 0.23458025 0.23947086]
0.999999360145845
4
[0.025428   0.25142149 0.25063088 0.23415124 0.23836839]
[0.02531242 0.25098107 0.25054237 0.23501737 0.23814678]
0.9999994082420891
0
[0.02488513 0.25070614 0.25387201 0.23194697 0.23858974]
[0.02573048 0.24933711 0.25615167 0.23160038 0.23718036]
0.9999918771743626
1
[0.02549145 0.2498827  0.2511313  0.23411399 0.23938056]
[0.02523575 0.24965576 0.25073833 0.23487689 0.23949327]
0.9999992581999828
2
[0.02577246 0.25128403 0.25012481 0.23393966 0.2388790

[0.02510795 0.25083827 0.25000267 0.23458025 0.23947086]
0.999999360145845
4
[0.025428   0.25142149 0.25063088 0.23415124 0.23836839]
[0.02531242 0.25098107 0.25054237 0.23501737 0.23814678]
0.9999994082420891
0
[0.02488513 0.25070614 0.25387201 0.23194697 0.23858974]
[0.02573048 0.24933711 0.25615167 0.23160038 0.23718036]
0.9999918771743626
1
[0.02549145 0.2498827  0.2511313  0.23411399 0.23938056]
[0.02523575 0.24965576 0.25073833 0.23487689 0.23949327]
0.9999992581999828
2
[0.02577246 0.25128403 0.25012481 0.23393966 0.23887904]
[0.02606203 0.25066748 0.25031754 0.23388732 0.23906563]
0.9999993680071122
3
[0.02522083 0.25113265 0.25061799 0.23395599 0.23907254]
[0.02511701 0.2509526  0.2499443  0.23451306 0.23947304]
0.9999994542405373
4
[0.02545665 0.2514044  0.25059114 0.23419359 0.23835421]
[0.02529909 0.2509651  0.25049389 0.23505821 0.23818371]
0.999999363424705
0
[0.02483296 0.25091006 0.25383082 0.23185634 0.23856983]
[0.02575151 0.2491849  0.25593668 0.23184942 0.23727749]


0
[0.02532973 0.2507452  0.25434149 0.23152601 0.23805757]
[0.02495195 0.24948152 0.25761425 0.23158735 0.23636492]
0.9999917500482998
1
[0.02544635 0.24990633 0.2510278  0.2341932  0.23942631]
[0.02516642 0.24964944 0.25077311 0.23493493 0.2394761 ]
0.9999992531135151
2
[0.02583551 0.25123923 0.25000636 0.23406993 0.23884897]
[0.02608042 0.25082999 0.24989172 0.23408406 0.23911382]
0.999999584397346
3
[0.02519654 0.25110567 0.25067265 0.23399423 0.23903091]
[0.02522402 0.2510971  0.24997182 0.23437698 0.23933008]
0.9999996259879262
4
[0.0253624  0.25136336 0.25057456 0.23410064 0.23859904]
[0.02522212 0.25124925 0.2508028  0.23519564 0.2375302 ]
0.999998631715776
0
[0.02518669 0.25083285 0.25399417 0.23180498 0.23818131]
[0.02511948 0.24896111 0.25746302 0.23173859 0.23671781]
0.9999912134591822
1
[0.02544899 0.24992628 0.25114283 0.23408745 0.23939444]
[0.02515748 0.24979612 0.25082857 0.23482021 0.23939762]
0.9999992362524502
2
[0.02579045 0.25125753 0.25007463 0.23400401 0.23887338

[0.02532559 0.25094443 0.2504428  0.23499651 0.23829067]
0.999999471920834
0
[0.02480634 0.25088331 0.25384081 0.2317961  0.23867344]
[0.02588304 0.24950596 0.25548878 0.23188052 0.23724171]
0.9999909203273015
1
[0.02548895 0.24987489 0.25110165 0.23413434 0.23940017]
[0.02529988 0.24980423 0.25061167 0.23475688 0.23952733]
0.9999994868443624
2
[0.02577583 0.25139825 0.25006342 0.23392694 0.23883556]
[0.02600731 0.25067712 0.25020798 0.23407326 0.23903434]
0.9999994398109864
3
[0.02524417 0.25105977 0.25063087 0.23393105 0.23913415]
[0.02517211 0.25093071 0.24998339 0.23437817 0.23953562]
0.9999995656943967
4
[0.02545356 0.25148219 0.25059888 0.23418058 0.23828479]
[0.02529885 0.25107543 0.25037088 0.2350131  0.23824173]
0.9999994035809664
0.28273233698425115 [ 1. -8.  1.]
0
[0.02542515 0.25004003 0.25562861 0.23130681 0.2375994 ]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999830565325551
1
[0.02556556 0.24963149 0.25132429 0.23357115 0.23990751]
[0.02535637 0.25039375

0
[0.02542515 0.25004003 0.25562861 0.23130681 0.2375994 ]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999830565325551
1
[0.02556556 0.24963149 0.25132429 0.23357115 0.23990751]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.9999957184752554
2
[0.02594877 0.25123391 0.25008896 0.23404788 0.23868048]
[0.02657282 0.25029826 0.24985295 0.23417711 0.23909886]
0.999997581506055
3
[0.02503966 0.25132976 0.25072027 0.23383587 0.23907445]
[0.02528393 0.25189968 0.24920543 0.23405073 0.23956024]
0.9999982467326796
4
[0.02523164 0.25165521 0.25055237 0.23445183 0.23810895]
[0.02555231 0.25130622 0.251512   0.23550955 0.23611993]
0.9999962939415873
0
[0.02530264 0.24972768 0.2536879  0.23293411 0.23834767]
[0.02482166 0.24798853 0.2603505  0.23067527 0.23616404]
0.9999704732922707
1
[0.02558464 0.24965469 0.2510898  0.23420499 0.23946588]
[0.0251487  0.24989035 0.25074431 0.23483635 0.2393803 ]
0.9999987599543787
2
[0.02579613 0.25099289 0.25014191 0.23442633 0.2386427

0
[0.02530264 0.24972768 0.2536879  0.23293411 0.23834767]
[0.02482166 0.24798853 0.2603505  0.23067527 0.23616404]
0.9999704732922707
1
[0.02558464 0.24965469 0.2510898  0.23420499 0.23946588]
[0.0251487  0.24989035 0.25074431 0.23483635 0.2393803 ]
0.9999987599543787
2
[0.02579613 0.25099289 0.25014191 0.23442633 0.23864275]
[0.02656949 0.25091473 0.24952062 0.23409901 0.23889614]
0.9999968575217946
3
[0.02519051 0.25135274 0.25061985 0.23382987 0.23900703]
[0.0252341  0.25138183 0.2496432  0.23420555 0.23953532]
0.9999992922887043
4
[0.02536073 0.25139603 0.25064432 0.23422553 0.23837339]
[0.02551045 0.25158176 0.25115624 0.23514332 0.23660823]
0.9999976535119113
0
[0.02523643 0.25070678 0.25352256 0.23227417 0.23826006]
[0.0243439  0.24910692 0.25798886 0.23187509 0.23668523]
0.9999835617284856
1
[0.02549355 0.24968675 0.25101614 0.23434104 0.23946251]
[0.02515257 0.2494822  0.25089107 0.23476768 0.23970649]
0.9999992692608727
2
[0.02580938 0.2509456  0.25002806 0.23434099 0.238875

0
[0.02523643 0.25070678 0.25352256 0.23227417 0.23826006]
[0.0243439  0.24910692 0.25798886 0.23187509 0.23668523]
0.9999835617284856
1
[0.02549355 0.24968675 0.25101614 0.23434104 0.23946251]
[0.02515257 0.2494822  0.25089107 0.23476768 0.23970649]
0.9999992692608727
2
[0.02580938 0.2509456  0.25002806 0.23434099 0.23887597]
[0.02646758 0.25116896 0.24956493 0.23395999 0.23883854]
0.9999977177317976
3
[0.02515159 0.25120535 0.25063675 0.23418115 0.23882516]
[0.02517953 0.25107515 0.24990183 0.23470442 0.23913907]
0.9999995203832991
4
[0.02546381 0.25123361 0.25064953 0.23425145 0.2384016 ]
[0.0253442  0.25180498 0.25096091 0.23509914 0.23679077]
0.9999979711642383
0
[0.02515984 0.25072534 0.25405858 0.23170682 0.23834943]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999855068671577
1
[0.02545475 0.24985272 0.2510919  0.23430979 0.23929085]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991078965915
2
[0.02579915 0.25101411 0.25010846 0.234193   0.238885

0
[0.02523643 0.25070678 0.25352256 0.23227417 0.23826006]
[0.0243439  0.24910692 0.25798886 0.23187509 0.23668523]
0.9999835617284856
1
[0.02549355 0.24968675 0.25101614 0.23434104 0.23946251]
[0.02515257 0.2494822  0.25089107 0.23476768 0.23970649]
0.9999992692608727
2
[0.02580938 0.2509456  0.25002806 0.23434099 0.23887597]
[0.02646758 0.25116896 0.24956493 0.23395999 0.23883854]
0.9999977177317976
3
[0.02515159 0.25120535 0.25063675 0.23418115 0.23882516]
[0.02517953 0.25107515 0.24990183 0.23470442 0.23913907]
0.9999995203832991
4
[0.02546381 0.25123361 0.25064953 0.23425145 0.2384016 ]
[0.0253442  0.25180498 0.25096091 0.23509914 0.23679077]
0.9999979711642383
0
[0.02515984 0.25072534 0.25405858 0.23170682 0.23834943]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999855068671577
1
[0.02545475 0.24985272 0.2510919  0.23430979 0.23929085]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991078965915
2
[0.02579915 0.25101411 0.25010846 0.234193   0.238885

0
[0.02523643 0.25070678 0.25352256 0.23227417 0.23826006]
[0.0243439  0.24910692 0.25798886 0.23187509 0.23668523]
0.9999835617284856
1
[0.02549355 0.24968675 0.25101614 0.23434104 0.23946251]
[0.02515257 0.2494822  0.25089107 0.23476768 0.23970649]
0.9999992692608727
2
[0.02580938 0.2509456  0.25002806 0.23434099 0.23887597]
[0.02646758 0.25116896 0.24956493 0.23395999 0.23883854]
0.9999977177317976
3
[0.02515159 0.25120535 0.25063675 0.23418115 0.23882516]
[0.02517953 0.25107515 0.24990183 0.23470442 0.23913907]
0.9999995203832991
4
[0.02546381 0.25123361 0.25064953 0.23425145 0.2384016 ]
[0.0253442  0.25180498 0.25096091 0.23509914 0.23679077]
0.9999979711642383
0
[0.02515984 0.25072534 0.25405858 0.23170682 0.23834943]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999855068671577
1
[0.02545475 0.24985272 0.2510919  0.23430979 0.23929085]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991078965915
2
[0.02579915 0.25101411 0.25010846 0.234193   0.238885

[0.0253442  0.25180498 0.25096091 0.23509914 0.23679077]
0.9999979711642383
0
[0.02515984 0.25072534 0.25405858 0.23170682 0.23834943]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999855068671577
1
[0.02545475 0.24985272 0.2510919  0.23430979 0.23929085]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991078965915
2
[0.02579915 0.25101411 0.25010846 0.234193   0.23888529]
[0.02624714 0.2512105  0.2495281  0.23411729 0.23889698]
0.9999988450952495
3
[0.02524115 0.25102411 0.25065854 0.23415974 0.23891646]
[0.02516381 0.25103481 0.2498345  0.23447605 0.23949083]
0.9999994053199063
4
[0.02545519 0.25127824 0.25055537 0.2340911  0.2386201 ]
[0.02536745 0.25149892 0.25099405 0.23515989 0.23697969]
0.9999978189018411
0
[0.0252999  0.25084858 0.2539441  0.23187201 0.23803542]
[0.02478257 0.24909606 0.25764357 0.23218997 0.23628783]
0.9999887758906358
1
[0.0254597  0.24980619 0.25106928 0.23429393 0.2393709 ]
[0.02516099 0.24979764 0.2506948  0.23482173 0.23952484

0
[0.02488513 0.25070614 0.25387201 0.23194697 0.23858974]
[0.02573048 0.24933711 0.25615167 0.23160038 0.23718036]
0.9999918771743626
1
[0.02549145 0.2498827  0.2511313  0.23411399 0.23938056]
[0.02523575 0.24965576 0.25073833 0.23487689 0.23949327]
0.9999992581999828
2
[0.02577246 0.25128403 0.25012481 0.23393966 0.23887904]
[0.02606203 0.25066748 0.25031754 0.23388732 0.23906563]
0.9999993680071122
3
[0.02522083 0.25113265 0.25061799 0.23395599 0.23907254]
[0.02511701 0.2509526  0.2499443  0.23451306 0.23947304]
0.9999994542405373
4
[0.02545665 0.2514044  0.25059114 0.23419359 0.23835421]
[0.02529909 0.2509651  0.25049389 0.23505821 0.23818371]
0.999999363424705
0
[0.02483296 0.25091006 0.25383082 0.23185634 0.23856983]
[0.02575151 0.2491849  0.25593668 0.23184942 0.23727749]
0.9999912896241292
1
[0.02549542 0.24986234 0.25110208 0.23412758 0.23941259]
[0.02526243 0.2497594  0.25070821 0.23478862 0.23948134]
0.9999994146015553
2
[0.02578729 0.25138328 0.25004497 0.23390491 0.2388795

0
[0.02507067 0.25103963 0.25386794 0.23173209 0.23828967]
[0.02538763 0.24876217 0.25686912 0.2318398  0.23714127]
0.9999917991663752
1
[0.02544898 0.24987064 0.25110245 0.23413546 0.23944247]
[0.02522637 0.24975619 0.25063923 0.23489907 0.23947915]
0.9999993305406453
2
[0.02577276 0.25122872 0.25013972 0.23396582 0.23889297]
[0.02605148 0.2507386  0.25028995 0.2338103  0.23910966]
0.9999994568566866
3
[0.02522884 0.25112963 0.25070577 0.23396013 0.23897563]
[0.0250993  0.25104816 0.24992081 0.23456102 0.23937071]
0.9999993313989548
4
[0.02540915 0.25145472 0.25066476 0.23411058 0.23836079]
[0.02530249 0.25110174 0.25067665 0.23503737 0.23788175]
0.9999993036778413
0
[0.02494262 0.25103077 0.25390515 0.231831   0.23829045]
[0.02554915 0.24932046 0.25621175 0.2319149  0.23700374]
0.9999932348217908
1
[0.02545964 0.24987208 0.25111866 0.23412318 0.23942644]
[0.02523712 0.2498525  0.25058869 0.23492496 0.23939673]
0.9999992725775417
2
[0.02577631 0.25125413 0.25020125 0.23388525 0.238883

2
[0.02577246 0.25128403 0.25012481 0.23393966 0.23887904]
[0.02606203 0.25066748 0.25031754 0.23388732 0.23906563]
0.9999993680071122
3
[0.02522083 0.25113265 0.25061799 0.23395599 0.23907254]
[0.02511701 0.2509526  0.2499443  0.23451306 0.23947304]
0.9999994542405373
4
[0.02545665 0.2514044  0.25059114 0.23419359 0.23835421]
[0.02529909 0.2509651  0.25049389 0.23505821 0.23818371]
0.999999363424705
0
[0.02483296 0.25091006 0.25383082 0.23185634 0.23856983]
[0.02575151 0.2491849  0.25593668 0.23184942 0.23727749]
0.9999912896241292
1
[0.02549542 0.24986234 0.25110208 0.23412758 0.23941259]
[0.02526243 0.2497594  0.25070821 0.23478862 0.23948134]
0.9999994146015553
2
[0.02578729 0.25138328 0.25004497 0.23390491 0.23887956]
[0.02601391 0.25059585 0.25032485 0.23403209 0.2390333 ]
0.9999993832007589
3
[0.02523481 0.25112399 0.2505906  0.23392309 0.2391275 ]
[0.02514448 0.25098272 0.25003179 0.23443026 0.23941075]
0.9999996144105632
4
[0.02544964 0.25141726 0.25058398 0.23420967 0.2383394

0
[0.02507067 0.25103963 0.25386794 0.23173209 0.23828967]
[0.02538763 0.24876217 0.25686912 0.2318398  0.23714127]
0.9999917991663752
1
[0.02544898 0.24987064 0.25110245 0.23413546 0.23944247]
[0.02522637 0.24975619 0.25063923 0.23489907 0.23947915]
0.9999993305406453
2
[0.02577276 0.25122872 0.25013972 0.23396582 0.23889297]
[0.02605148 0.2507386  0.25028995 0.2338103  0.23910966]
0.9999994568566866
3
[0.02522884 0.25112963 0.25070577 0.23396013 0.23897563]
[0.0250993  0.25104816 0.24992081 0.23456102 0.23937071]
0.9999993313989548
4
[0.02540915 0.25145472 0.25066476 0.23411058 0.23836079]
[0.02530249 0.25110174 0.25067665 0.23503737 0.23788175]
0.9999993036778413
0
[0.02494262 0.25103077 0.25390515 0.231831   0.23829045]
[0.02554915 0.24932046 0.25621175 0.2319149  0.23700374]
0.9999932348217908
1
[0.02545964 0.24987208 0.25111866 0.23412318 0.23942644]
[0.02523712 0.2498525  0.25058869 0.23492496 0.23939673]
0.9999992725775417
2
[0.02577631 0.25125413 0.25020125 0.23388525 0.238883

0
[0.02532973 0.2507452  0.25434149 0.23152601 0.23805757]
[0.02495195 0.24948152 0.25761425 0.23158735 0.23636492]
0.9999917500482998
1
[0.02544635 0.24990633 0.2510278  0.2341932  0.23942631]
[0.02516642 0.24964944 0.25077311 0.23493493 0.2394761 ]
0.9999992531135151
2
[0.02583551 0.25123923 0.25000636 0.23406993 0.23884897]
[0.02608042 0.25082999 0.24989172 0.23408406 0.23911382]
0.999999584397346
3
[0.02519654 0.25110567 0.25067265 0.23399423 0.23903091]
[0.02522402 0.2510971  0.24997182 0.23437698 0.23933008]
0.9999996259879262
4
[0.0253624  0.25136336 0.25057456 0.23410064 0.23859904]
[0.02522212 0.25124925 0.2508028  0.23519564 0.2375302 ]
0.999998631715776
0
[0.02518669 0.25083285 0.25399417 0.23180498 0.23818131]
[0.02511948 0.24896111 0.25746302 0.23173859 0.23671781]
0.9999912134591822
1
[0.02544899 0.24992628 0.25114283 0.23408745 0.23939444]
[0.02515748 0.24979612 0.25082857 0.23482021 0.23939762]
0.9999992362524502
2
[0.02579045 0.25125753 0.25007463 0.23400401 0.23887338

0
[0.02518669 0.25083285 0.25399417 0.23180498 0.23818131]
[0.02511948 0.24896111 0.25746302 0.23173859 0.23671781]
0.9999912134591822
1
[0.02544899 0.24992628 0.25114283 0.23408745 0.23939444]
[0.02515748 0.24979612 0.25082857 0.23482021 0.23939762]
0.9999992362524502
2
[0.02579045 0.25125753 0.25007463 0.23400401 0.23887338]
[0.0260843  0.25088173 0.25013637 0.23377025 0.23912735]
0.9999994487097007
3
[0.02520939 0.25108749 0.25075438 0.23398391 0.23896483]
[0.02506682 0.25111871 0.2498964  0.23459731 0.23932076]
0.9999992638991961
4
[0.02536036 0.25143728 0.25055467 0.23416557 0.23848212]
[0.02531563 0.25129625 0.25060814 0.23508602 0.23769396]
0.9999992013147282
0
[0.02507067 0.25103963 0.25386794 0.23173209 0.23828967]
[0.02538763 0.24876217 0.25686912 0.2318398  0.23714127]
0.9999917991663752
1
[0.02544898 0.24987064 0.25110245 0.23413546 0.23944247]
[0.02522637 0.24975619 0.25063923 0.23489907 0.23947915]
0.9999993305406453
2
[0.02577276 0.25122872 0.25013972 0.23396582 0.238892

0
[0.02518669 0.25083285 0.25399417 0.23180498 0.23818131]
[0.02511948 0.24896111 0.25746302 0.23173859 0.23671781]
0.9999912134591822
1
[0.02544899 0.24992628 0.25114283 0.23408745 0.23939444]
[0.02515748 0.24979612 0.25082857 0.23482021 0.23939762]
0.9999992362524502
2
[0.02579045 0.25125753 0.25007463 0.23400401 0.23887338]
[0.0260843  0.25088173 0.25013637 0.23377025 0.23912735]
0.9999994487097007
3
[0.02520939 0.25108749 0.25075438 0.23398391 0.23896483]
[0.02506682 0.25111871 0.2498964  0.23459731 0.23932076]
0.9999992638991961
4
[0.02536036 0.25143728 0.25055467 0.23416557 0.23848212]
[0.02531563 0.25129625 0.25060814 0.23508602 0.23769396]
0.9999992013147282
0
[0.02507067 0.25103963 0.25386794 0.23173209 0.23828967]
[0.02538763 0.24876217 0.25686912 0.2318398  0.23714127]
0.9999917991663752
1
[0.02544898 0.24987064 0.25110245 0.23413546 0.23944247]
[0.02522637 0.24975619 0.25063923 0.23489907 0.23947915]
0.9999993305406453
2
[0.02577276 0.25122872 0.25013972 0.23396582 0.238892

0
[0.02518669 0.25083285 0.25399417 0.23180498 0.23818131]
[0.02511948 0.24896111 0.25746302 0.23173859 0.23671781]
0.9999912134591822
1
[0.02544899 0.24992628 0.25114283 0.23408745 0.23939444]
[0.02515748 0.24979612 0.25082857 0.23482021 0.23939762]
0.9999992362524502
2
[0.02579045 0.25125753 0.25007463 0.23400401 0.23887338]
[0.0260843  0.25088173 0.25013637 0.23377025 0.23912735]
0.9999994487097007
3
[0.02520939 0.25108749 0.25075438 0.23398391 0.23896483]
[0.02506682 0.25111871 0.2498964  0.23459731 0.23932076]
0.9999992638991961
4
[0.02536036 0.25143728 0.25055467 0.23416557 0.23848212]
[0.02531563 0.25129625 0.25060814 0.23508602 0.23769396]
0.9999992013147282
0
[0.02507067 0.25103963 0.25386794 0.23173209 0.23828967]
[0.02538763 0.24876217 0.25686912 0.2318398  0.23714127]
0.9999917991663752
1
[0.02544898 0.24987064 0.25110245 0.23413546 0.23944247]
[0.02522637 0.24975619 0.25063923 0.23489907 0.23947915]
0.9999993305406453
2
[0.02577276 0.25122872 0.25013972 0.23396582 0.238892

0
[0.02483296 0.25091006 0.25383082 0.23185634 0.23856983]
[0.02575151 0.2491849  0.25593668 0.23184942 0.23727749]
0.9999912896241292
1
[0.02549542 0.24986234 0.25110208 0.23412758 0.23941259]
[0.02526243 0.2497594  0.25070821 0.23478862 0.23948134]
0.9999994146015553
2
[0.02578729 0.25138328 0.25004497 0.23390491 0.23887956]
[0.02601391 0.25059585 0.25032485 0.23403209 0.2390333 ]
0.9999993832007589
3
[0.02523481 0.25112399 0.2505906  0.23392309 0.2391275 ]
[0.02514448 0.25098272 0.25003179 0.23443026 0.23941075]
0.9999996144105632
4
[0.02544964 0.25141726 0.25058398 0.23420967 0.23833945]
[0.02532559 0.25094443 0.2504428  0.23499651 0.23829067]
0.999999471920834
0
[0.02480634 0.25088331 0.25384081 0.2317961  0.23867344]
[0.02588304 0.24950596 0.25548878 0.23188052 0.23724171]
0.9999909203273015
1
[0.02548895 0.24987489 0.25110165 0.23413434 0.23940017]
[0.02529988 0.24980423 0.25061167 0.23475688 0.23952733]
0.9999994868443624
2
[0.02577583 0.25139825 0.25006342 0.23392694 0.2388355

0
[0.02542515 0.25004003 0.25562861 0.23130681 0.2375994 ]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999830565325551
1
[0.02556556 0.24963149 0.25132429 0.23357115 0.23990751]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.9999957184752554
2
[0.02594877 0.25123391 0.25008896 0.23404788 0.23868048]
[0.02657282 0.25029826 0.24985295 0.23417711 0.23909886]
0.999997581506055
3
[0.02503966 0.25132976 0.25072027 0.23383587 0.23907445]
[0.02528393 0.25189968 0.24920543 0.23405073 0.23956024]
0.9999982467326796
4
[0.02523164 0.25165521 0.25055237 0.23445183 0.23810895]
[0.02555231 0.25130622 0.251512   0.23550955 0.23611993]
0.9999962939415873
0
[0.02530264 0.24972768 0.2536879  0.23293411 0.23834767]
[0.02482166 0.24798853 0.2603505  0.23067527 0.23616404]
0.9999704732922707
1
[0.02558464 0.24965469 0.2510898  0.23420499 0.23946588]
[0.0251487  0.24989035 0.25074431 0.23483635 0.2393803 ]
0.9999987599543787
2
[0.02579613 0.25099289 0.25014191 0.23442633 0.2386427

0
[0.02523643 0.25070678 0.25352256 0.23227417 0.23826006]
[0.0243439  0.24910692 0.25798886 0.23187509 0.23668523]
0.9999835617284856
1
[0.02549355 0.24968675 0.25101614 0.23434104 0.23946251]
[0.02515257 0.2494822  0.25089107 0.23476768 0.23970649]
0.9999992692608727
2
[0.02580938 0.2509456  0.25002806 0.23434099 0.23887597]
[0.02646758 0.25116896 0.24956493 0.23395999 0.23883854]
0.9999977177317976
3
[0.02515159 0.25120535 0.25063675 0.23418115 0.23882516]
[0.02517953 0.25107515 0.24990183 0.23470442 0.23913907]
0.9999995203832991
4
[0.02546381 0.25123361 0.25064953 0.23425145 0.2384016 ]
[0.0253442  0.25180498 0.25096091 0.23509914 0.23679077]
0.9999979711642383
0
[0.02515984 0.25072534 0.25405858 0.23170682 0.23834943]
[0.02482166 0.24879475 0.2583146  0.23214926 0.23591974]
0.9999855068671577
1
[0.02545475 0.24985272 0.2510919  0.23430979 0.23929085]
[0.02510965 0.24960708 0.25078751 0.23487456 0.2396212 ]
0.9999991078965915
2
[0.02579915 0.25101411 0.25010846 0.234193   0.238885

0
[0.02480634 0.25088331 0.25384081 0.2317961  0.23867344]
[0.02588304 0.24950596 0.25548878 0.23188052 0.23724171]
0.9999909203273015
1
[0.02548895 0.24987489 0.25110165 0.23413434 0.23940017]
[0.02529988 0.24980423 0.25061167 0.23475688 0.23952733]
0.9999994868443624
2
[0.02577583 0.25139825 0.25006342 0.23392694 0.23883556]
[0.02600731 0.25067712 0.25020798 0.23407326 0.23903434]
0.9999994398109864
3
[0.02524417 0.25105977 0.25063087 0.23393105 0.23913415]
[0.02517211 0.25093071 0.24998339 0.23437817 0.23953562]
0.9999995656943967
4
[0.02545356 0.25148219 0.25059888 0.23418058 0.23828479]
[0.02529885 0.25107543 0.25037088 0.2350131  0.23824173]
0.9999994035809664
0.28273233698425115 [ 1. -8.  1.]
0
[0.02542515 0.25004003 0.25562861 0.23130681 0.2375994 ]
[0.02472393 0.24818398 0.26039936 0.22958403 0.2371087 ]
0.9999830565325551
1
[0.02556556 0.24963149 0.25132429 0.23357115 0.23990751]
[0.02535637 0.25039375 0.25112145 0.23527496 0.23785346]
0.9999957184752554
2
[0.02594877 0.25123

0
[0.02483296 0.25091006 0.25383082 0.23185634 0.23856983]
[0.02575151 0.2491849  0.25593668 0.23184942 0.23727749]
0.9999912896241292
1
[0.02549542 0.24986234 0.25110208 0.23412758 0.23941259]
[0.02526243 0.2497594  0.25070821 0.23478862 0.23948134]
0.9999994146015553
2
[0.02578729 0.25138328 0.25004497 0.23390491 0.23887956]
[0.02601391 0.25059585 0.25032485 0.23403209 0.2390333 ]
0.9999993832007589
3
[0.02523481 0.25112399 0.2505906  0.23392309 0.2391275 ]
[0.02514448 0.25098272 0.25003179 0.23443026 0.23941075]
0.9999996144105632
4
[0.02544964 0.25141726 0.25058398 0.23420967 0.23833945]
[0.02532559 0.25094443 0.2504428  0.23499651 0.23829067]
0.999999471920834
0
[0.02480634 0.25088331 0.25384081 0.2317961  0.23867344]
[0.02588304 0.24950596 0.25548878 0.23188052 0.23724171]
0.9999909203273015
1
[0.02548895 0.24987489 0.25110165 0.23413434 0.23940017]
[0.02529988 0.24980423 0.25061167 0.23475688 0.23952733]
0.9999994868443624
2
[0.02577583 0.25139825 0.25006342 0.23392694 0.2388355

In [342]:
pars_in = pars_ref[0]
output = fmin(loss_sd2_hist, pars_in, args=(X_ref[0], pars_ref[0], beta_ref[0], hist_ref[0], hist_targ))

[0.02217415 0.22772579 0.23067028 0.20984925 0.21857788 0.09100265]
[0.02270365 0.22677667 0.23756009 0.20901    0.21680525 0.08714434]
0.9999494781124738
[0.02190257 0.22855006 0.23098473 0.2087677  0.2192735  0.09052143]
[0.02252501 0.2255749  0.23656944 0.21022801 0.21531116 0.08979148]
0.9999652265738994
[0.02192957 0.22885657 0.2298603  0.20931562 0.21942597 0.09061196]
[0.02247629 0.22613789 0.23538392 0.21078559 0.21514876 0.09006756]
0.9999656400159949
[0.0218049  0.22840474 0.2295792  0.20967534 0.21920442 0.0913314 ]
[0.02237073 0.22632194 0.23453131 0.2113161  0.21514876 0.09031116]
0.9999700941501011
[0.02198929 0.2283185  0.22937813 0.20968154 0.21932877 0.09130377]
[0.02261271 0.22667273 0.23490971 0.21121216 0.21472002 0.08987268]
0.9999634047547733
[0.02195022 0.22826577 0.22925521 0.20999854 0.21934815 0.09118211]
[0.0227632  0.22665757 0.23452319 0.21065567 0.21503508 0.09036529]
0.9999680410240857
[0.0219509  0.22823355 0.22920416 0.21027806 0.21917277 0.09116056]
[0

[0.02208611 0.22785799 0.22891239 0.21091191 0.21919721 0.09103438]
[0.02323633 0.2270495  0.23325971 0.21066    0.21568468 0.09010978]
0.999973808418559
0.13579296089228238 [-8.      -2.08725]
[0.02213495 0.22771581 0.23070543 0.20992727 0.21847736 0.09103918]
[0.02270365 0.22677667 0.23756009 0.20901    0.21680525 0.08714434]
0.9999492305790411
[0.02189185 0.22851822 0.23101472 0.20882476 0.21920673 0.09054372]
[0.02252501 0.2255749  0.23656944 0.21022801 0.21531116 0.08979148]
0.9999657857118613
[0.02191057 0.22883855 0.22991156 0.20930128 0.21941469 0.09062335]
[0.02247629 0.22613789 0.23538392 0.21078559 0.21514876 0.09006756]
0.99996589092864
[0.02178151 0.22834083 0.22963805 0.20971524 0.21918079 0.09134358]
[0.02237073 0.22632194 0.23453131 0.2113161  0.21514876 0.09031116]
0.9999705499439558
[0.02198045 0.22826404 0.22942133 0.20969536 0.21929845 0.09134037]
[0.02261271 0.22667273 0.23490971 0.21121216 0.21472002 0.08987268]
0.9999637354556729
[0.02194483 0.22823903 0.2293115 

[0.02197795 0.22824361 0.22943268 0.20970838 0.21928707 0.09135031]
[0.02261271 0.22667273 0.23490971 0.21121216 0.21472002 0.08987268]
0.9999638632831296
[0.0219414  0.22823042 0.22932672 0.21000346 0.21927903 0.09121897]
[0.0227632  0.22665757 0.23452319 0.21065567 0.21503508 0.09036529]
0.9999686850174478
[0.02194904 0.22821523 0.22924468 0.21028762 0.2191125  0.09119093]
[0.02261549 0.22644258 0.23427031 0.21059225 0.2153158  0.09076356]
0.9999735558816368
[0.021968   0.22814907 0.22929225 0.21027336 0.2192249  0.09109242]
[0.02294725 0.2262042  0.23400351 0.21066243 0.21563596 0.09054664]
0.9999726980952441
[0.02201316 0.22800818 0.22904358 0.21073538 0.21914232 0.09105738]
[0.02307176 0.22660344 0.23365164 0.21060514 0.21566122 0.0904068 ]
0.9999736657155279
[0.02208465 0.22784112 0.22893088 0.210922   0.21918007 0.09104128]
[0.02323633 0.2270495  0.23325971 0.21066    0.21568468 0.09010978]
0.9999739397868801
0.13485252066070746 [-8.  1.]
[0.02211458 0.22770379 0.23073639 0.2099

[0.02190216 0.22882424 0.22994391 0.20929525 0.21940971 0.09062475]
[0.02247629 0.22613789 0.23538392 0.21078559 0.21514876 0.09006756]
0.9999660810754702
[0.02177485 0.22831372 0.22965897 0.20973404 0.21917359 0.09134483]
[0.02237073 0.22632194 0.23453131 0.2113161  0.21514876 0.09031116]
0.9999707404714702
[0.02197795 0.22824361 0.22943268 0.20970838 0.21928707 0.09135031]
[0.02261271 0.22667273 0.23490971 0.21121216 0.21472002 0.08987268]
0.9999638632831296
[0.0219414  0.22823042 0.22932672 0.21000346 0.21927903 0.09121897]
[0.0227632  0.22665757 0.23452319 0.21065567 0.21503508 0.09036529]
0.9999686850174478
[0.02194904 0.22821523 0.22924468 0.21028762 0.2191125  0.09119093]
[0.02261549 0.22644258 0.23427031 0.21059225 0.2153158  0.09076356]
0.9999735558816368
[0.021968   0.22814907 0.22929225 0.21027336 0.2192249  0.09109242]
[0.02294725 0.2262042  0.23400351 0.21066243 0.21563596 0.09054664]
0.9999726980952441
[0.02201316 0.22800818 0.22904358 0.21073538 0.21914232 0.09105738]
[0

[0.02188371 0.22849828 0.23104032 0.2088437  0.21919239 0.0905416 ]
[0.02252501 0.2255749  0.23656944 0.21022801 0.21531116 0.08979148]
0.9999660436490166
[0.02190216 0.22882424 0.22994391 0.20929525 0.21940971 0.09062475]
[0.02247629 0.22613789 0.23538392 0.21078559 0.21514876 0.09006756]
0.9999660810754702
[0.02177485 0.22831372 0.22965897 0.20973404 0.21917359 0.09134483]
[0.02237073 0.22632194 0.23453131 0.2113161  0.21514876 0.09031116]
0.9999707404714702
[0.02197795 0.22824361 0.22943268 0.20970838 0.21928707 0.09135031]
[0.02261271 0.22667273 0.23490971 0.21121216 0.21472002 0.08987268]
0.9999638632831296
[0.0219414  0.22823042 0.22932672 0.21000346 0.21927903 0.09121897]
[0.0227632  0.22665757 0.23452319 0.21065567 0.21503508 0.09036529]
0.9999686850174478
[0.02194904 0.22821523 0.22924468 0.21028762 0.2191125  0.09119093]
[0.02261549 0.22644258 0.23427031 0.21059225 0.2153158  0.09076356]
0.9999735558816368
[0.021968   0.22814907 0.22929225 0.21027336 0.2192249  0.09109242]
[0

[0.02188371 0.22849828 0.23104032 0.2088437  0.21919239 0.0905416 ]
[0.02252501 0.2255749  0.23656944 0.21022801 0.21531116 0.08979148]
0.9999660436490166
[0.02190216 0.22882424 0.22994391 0.20929525 0.21940971 0.09062475]
[0.02247629 0.22613789 0.23538392 0.21078559 0.21514876 0.09006756]
0.9999660810754702
[0.02177485 0.22831372 0.22965897 0.20973404 0.21917359 0.09134483]
[0.02237073 0.22632194 0.23453131 0.2113161  0.21514876 0.09031116]
0.9999707404714702
[0.02197795 0.22824361 0.22943268 0.20970838 0.21928707 0.09135031]
[0.02261271 0.22667273 0.23490971 0.21121216 0.21472002 0.08987268]
0.9999638632831296
[0.0219414  0.22823042 0.22932672 0.21000346 0.21927903 0.09121897]
[0.0227632  0.22665757 0.23452319 0.21065567 0.21503508 0.09036529]
0.9999686850174478
[0.02194904 0.22821523 0.22924468 0.21028762 0.2191125  0.09119093]
[0.02261549 0.22644258 0.23427031 0.21059225 0.2153158  0.09076356]
0.9999735558816368
[0.021968   0.22814907 0.22929225 0.21027336 0.2192249  0.09109242]
[0

[0.02201316 0.22800818 0.22904358 0.21073538 0.21914232 0.09105738]
[0.02307176 0.22660344 0.23365164 0.21060514 0.21566122 0.0904068 ]
0.9999736657155279
[0.02208465 0.22784112 0.22893088 0.210922   0.21918007 0.09104128]
[0.02323633 0.2270495  0.23325971 0.21066    0.21568468 0.09010978]
0.9999739397868801
0.13485252066070746 [-8.  1.]
[0.02211458 0.22770379 0.23073639 0.20994903 0.21844492 0.09105129]
[0.02270365 0.22677667 0.23756009 0.20901    0.21680525 0.08714434]
0.9999492446036857
[0.02188371 0.22849828 0.23104032 0.2088437  0.21919239 0.0905416 ]
[0.02252501 0.2255749  0.23656944 0.21022801 0.21531116 0.08979148]
0.9999660436490166
[0.02190216 0.22882424 0.22994391 0.20929525 0.21940971 0.09062475]
[0.02247629 0.22613789 0.23538392 0.21078559 0.21514876 0.09006756]
0.9999660810754702
[0.02177485 0.22831372 0.22965897 0.20973404 0.21917359 0.09134483]
[0.02237073 0.22632194 0.23453131 0.2113161  0.21514876 0.09031116]
0.9999707404714702
[0.02197795 0.22824361 0.22943268 0.2097

[0.02188371 0.22849828 0.23104032 0.2088437  0.21919239 0.0905416 ]
[0.02252501 0.2255749  0.23656944 0.21022801 0.21531116 0.08979148]
0.9999660436490166
[0.02190216 0.22882424 0.22994391 0.20929525 0.21940971 0.09062475]
[0.02247629 0.22613789 0.23538392 0.21078559 0.21514876 0.09006756]
0.9999660810754702
[0.02177485 0.22831372 0.22965897 0.20973404 0.21917359 0.09134483]
[0.02237073 0.22632194 0.23453131 0.2113161  0.21514876 0.09031116]
0.9999707404714702
[0.02197795 0.22824361 0.22943268 0.20970838 0.21928707 0.09135031]
[0.02261271 0.22667273 0.23490971 0.21121216 0.21472002 0.08987268]
0.9999638632831296
[0.0219414  0.22823042 0.22932672 0.21000346 0.21927903 0.09121897]
[0.0227632  0.22665757 0.23452319 0.21065567 0.21503508 0.09036529]
0.9999686850174478
[0.02194904 0.22821523 0.22924468 0.21028762 0.2191125  0.09119093]
[0.02261549 0.22644258 0.23427031 0.21059225 0.2153158  0.09076356]
0.9999735558816368
[0.021968   0.22814907 0.22929225 0.21027336 0.2192249  0.09109242]
[0

In [59]:
pars_ref[:], pars_list

([array([-2.97, -7.  , -4.  ])],
 [array([ 0.  , -2.97, -7.  , -1.05, -4.  ,  0.  , -0.78, -0.06, -0.48,
          0.  , -0.24, -0.17,  0.  ,  0.04,  0.  ])])

In [362]:
loss_sd2_hist(np.array([-5.44, -5.06]), X_ref[0], pars_ref[0], beta_ref[0], hist_ref[0], hist_targ)

0
[0.02217415 0.22772579 0.23067028 0.20984925 0.21857788 0.09100265]
[0.02270365 0.22677667 0.23756009 0.20901    0.21680525 0.08714434]
0.9999494781124738
1
[0.02329492 0.22705077 0.22802042 0.21291712 0.21757921 0.09113758]
[0.02334638 0.2283862  0.22862152 0.21506246 0.21700799 0.08757544]
0.9999781808303895
2
[0.0235626  0.22837096 0.22623684 0.21267452 0.21806123 0.09109384]
[0.02424319 0.22799004 0.22757571 0.21341231 0.21787711 0.08890163]
0.9999894966391973
3
[0.02273943 0.22782826 0.22832975 0.2128583  0.21732499 0.09091928]
[0.02299438 0.22970954 0.22732065 0.21343812 0.21862765 0.08790967]
0.9999833183191307
4
[0.0232005  0.2276179  0.22812949 0.21273592 0.21750473 0.09081146]
[0.02346861 0.22945888 0.229518   0.21476839 0.21448321 0.08830291]
0.9999802250176928
5
[0.02305648 0.22760919 0.22813931 0.21223337 0.21809371 0.09086794]
[0.02312967 0.22453915 0.22450602 0.20746311 0.21409643 0.10626563]
0.9996635403132106
0
[0.02190257 0.22855006 0.23098473 0.2087677  0.2192735  

6.574445524761564

In [363]:
X_ref[0][-1], X_ref[1][-2]

(array([141, 105]), array([161, 104]))

In [364]:
# loss_sd2_hist(np.array([-7., -4.]), X_ref[0], pars_ref[0], beta_ref[0], hist_ref[0], hist_targ)

0
[0.02216507 0.2277279  0.23067004 0.2098804  0.21854046 0.09101612]
[0.02270365 0.22677667 0.23756009 0.20901    0.21680525 0.08714434]
0.9999493186530525
1
[0.02329583 0.22703052 0.22803246 0.21292995 0.21757022 0.09114101]
[0.02334638 0.2283862  0.22862152 0.21506246 0.21700799 0.08757544]
0.9999781632938969
2
[0.02356245 0.22836014 0.22625112 0.21267451 0.21804447 0.09110732]
[0.02424319 0.22799004 0.22757571 0.21341231 0.21787711 0.08890163]
0.999989442502041
3
[0.02273402 0.22782947 0.22832582 0.21287246 0.21733    0.09090823]
[0.02299438 0.22970954 0.22732065 0.21343812 0.21862765 0.08790967]
0.9999834189373424
4
[0.0232009  0.22761029 0.22813811 0.21273997 0.21751972 0.090791  ]
[0.02346861 0.22945888 0.229518   0.21476839 0.21448321 0.08830291]
0.9999803228383659
5
[0.02305554 0.22757641 0.22819622 0.21223844 0.21806621 0.09086718]
[0.02312967 0.22453915 0.22450602 0.20746311 0.21409643 0.10626563]
0.9996634873642769
0
[0.02190213 0.22854497 0.23098382 0.20878826 0.21924384 0

6.57448816626807

In [365]:
loss_sd2_hist(np.array([-7., -4.]), X_ref[1], pars_ref[1], beta_ref[1], hist_ref[1], hist_targ)

0
[0.02151574 0.23008005 0.22879197 0.21111185 0.21813428 0.0903661 ]
[0.02270365 0.22677667 0.23756009 0.20901    0.21680525 0.08714434]
0.9999265680773258
1
[0.02331377 0.22738764 0.22772634 0.2125209  0.21842431 0.09062703]
[0.02334638 0.2283862  0.22862152 0.21506246 0.21700799 0.08757544]
0.9999810148008674
2
[0.02327712 0.22791219 0.22726153 0.21222279 0.21817274 0.09115363]
[0.02424319 0.22799004 0.22757571 0.21341231 0.21787711 0.08890163]
0.9999871089987679
3
[0.02272127 0.22805116 0.22797522 0.21270252 0.21742238 0.09112746]
[0.02299438 0.22970954 0.22732065 0.21343812 0.21862765 0.08790967]
0.9999822452077978
4
[0.02306455 0.22742091 0.22858582 0.21240103 0.21736229 0.09116539]
[0.02346861 0.22945888 0.229518   0.21476839 0.21448321 0.08830291]
0.9999768824814581
5
[0.02309589 0.22739428 0.22752774 0.21287138 0.21797684 0.09113388]
[0.02312967 0.22453915 0.22450602 0.20746311 0.21409643 0.10626563]
0.9996739144847849
0
[0.02217886 0.22880628 0.22997033 0.20942303 0.21826309 

6.716010197274094

In [255]:
loss_sd2_hist(np.array([-7.0, -4.0]), X_ref[0], pars_ref[0], beta_ref[0], hist_ref[0], hist_targ)

[0.02206824 0.22695578 0.2312463  0.2117187  0.21737919 0.0906318 ]
[0.02270365 0.22677667 0.23756009 0.20901    0.21680525 0.08714434]
0.999954813962649
0.0038021500690616243 [-7. -4.]


0.0038021500690616243

## Compare distributions, statistical testing

In [27]:
for i, k in enumerate(targets.keys()):
    if k > 200:
        continue
    print('null')
    get_s2_two(k, targets[k], null_counts[k])
#     print('txinf')
#     get_s2_two(k, targets[k], knn_all['txinf'][i])
#     print('tx700')
#     get_s2_two(k, targets[k], knn_all['tx700'][i])
#     print('tx500')
#     get_s2_two(k, targets[k], knn_all['tx500'][i])
    print('1x700')
    get_s2_two(k, targets[k], knn_all['1x700'][i])

null
0 [ 699 6982 7314 6435 6675 2683] [ 715.82589416 7014.96821189 7014.41020808 6550.05803327 6685.18795716
 2807.54969544] [ -16.82589416  -32.96821189  299.58979192 -115.05803327  -10.18795716
 -124.54969544]
1 0 p-value 0.06477022670197327
1 [ 7044 68908 68979 64888 65475 26423] [ 7014.96821189 68745.45810017 68739.98976066 64189.41989162
 65513.66944494 27513.49459072] [   29.03178811   162.54189983   239.01023934   698.58010838
   -38.66944494 -1090.49459072]
1 1 p-value 7.107498401190488e-05
2 [ 7314 68783 68658 64385 65732 26821] [ 7014.41020808 68739.98976066 68734.52185612 64184.31396097
 65508.4581772  27511.30603698] [ 299.58979192   43.01023934  -76.52185612  200.68603903  223.5418228
 -690.30603698]
1 2 p-value 0.007483190721920082
3 [ 6478 64714 64041 60130 61592 24766] [ 6550.05803327 64189.41989162 64184.31396097 59935.32867318
 61171.8148785  25690.06456246] [ -72.05803327  524.58010838 -143.31396097  194.67132682  420.1851215
 -924.06456246]
1 3 p-value 0.0006887766

0 [ 4874 48802 50489 45386 46404 19561] [ 4854.24251119 49036.24159302 49463.50916255 45295.07379777
 47152.55403803 19714.37889743] [  19.75748881 -234.24159302 1025.49083745   90.92620223 -748.55403803
 -153.37889743]
7 0 p-value 4.547473927550435e-05
1 [ 48353 480116 482301 452122 460587 188540] [ 48802.86746767 479733.07288987 481592.4218316  449892.29081739
 459943.18114301 192055.16585045] [ -449.86746767   382.92711013   708.5781684   2229.70918261
   643.81885699 -3515.16585045]
7 1 p-value 2.045806987248768e-12
2 [ 50254 482122 480433 449732 460025 189285] [ 49216.07160707 481930.18379487 479879.16050305 448696.46534748
 459924.99839741 192204.12035012] [ 1037.92839293   191.81620513   553.83949695  1035.53465252
   100.00160259 -2919.12035012]
7 2 p-value 2.37741912295997e-10
3 [ 45051 451254 449022 421481 429955 175284] [ 45128.73684785 450348.5590962  449225.85317862 419521.29181232
 428408.64825423 179413.91081079] [  -77.73684785   905.4409038   -203.85317862  1959.708187

40 3 p-value 5.902804369896714e-41
4 [ 266366 2628203 2621686 2456121 2495756 1033188] [ 267407.51828643 2620546.77779741 2620338.32708808 2446872.59514003
 2497352.40858295 1048802.37310509] [ -1041.51828643   7656.22220259   1347.67291192   9248.40485997
  -1596.40858295 -15614.37310509]
40 4 p-value 2.6418330111670297e-30
5 [ 109971 1083446 1082970 1012553 1034562  506658] [ 112301.98781761 1100539.78362883 1100452.24147904 1027602.58249849
 1048802.37310509  440461.03147094] [ -2330.98781761 -17093.78362883 -17482.24147904 -15049.58249849
 -14240.37310509  66196.96852906]
40 5 p-value 0.0
1x700
0 [ 29110 279423 285460 260991 266525 110011] [ 27420.21282375 280704.19247102 281640.29419641 260054.30077662
 269358.7809021  112342.2188301 ] [ 1689.78717625 -1281.19247102  3819.70580359   936.69922338
 -2833.7809021  -2331.2188301 ]
40 0 p-value 3.0022190818624524e-38
1 [ 279459 2748873 2753290 2577326 2628427 1081305] [ 278877.20307188 2741901.88062306 2752754.56219961 2567412.75386286

In [ ]:
Al Fe Ni Cr Co
-16.82589416  -32.96821189  299.58979192 -115.05803327  -10.18795716 -124.54969544

In [28]:
 -16.82589416  -32.96821189  299.58979192 -115.05803327  -10.18795716 -124.54969544
20.47253984   11.75252954  194.89341128  -72.22808289   15.09589838 -169.98629614
18.87351129    3.42587269  232.80410678  -64.57453799 -103.62340862 -86.90554415


-24.30820551   -8.80891829  267.59700443 -145.58314801   10.44053525 -99.33726787

18.64444444    5.56239316  226.12991453  -82.77094017  -13.88888889 -153.67692308
18.87351129    3.42587269  232.80410678  -64.57453799 -103.62340862 -86.90554415
30.73242609   44.18882986  213.21814743 -100.79731438 -115.05498589 -72.28710312

-171.15009878  259.44646136 -294.4464846   140.7234631   169.98398605 -104.55732714

SyntaxError: invalid syntax (<ipython-input-28-99c728985025>, line 1)